using FusionRpg.Core.Effects.Atoms;

namespace FusionRpg.Tools.PassiveTreeRosterGen;

public sealed record AtomVocabMirror(
    IReadOnlyList<string> AttachPoints,
    IReadOnlyList<(string Id, string Attach)> Kinds,
    IReadOnlyList<(string Id, bool Authorable)> Triggers);

/// <summary>
/// Whether `data/seed/passive-tree/vocabulary.json` still agrees with the shipped
/// <see cref="AttachPoint"/> enum, <see cref="AtomKindRegistry"/> and <see cref="AtomTriggers"/>
/// (task A3) — 7 attach points, 16 kinds, 13 triggers (11 authorable — `OnGranted`/`OnRemoved` are
/// runtime lifecycle states, never authorable, per `AtomTriggers.Lifecycle`'s own doc comment).
/// </summary>
public static class AtomVocabCheck
{
    public static AtomVocabMirror LiveVocab()
    {
        var attachPoints = Enum.GetNames<AttachPoint>().OrderBy(n => n, StringComparer.Ordinal).ToList();
        var kinds = AtomKindRegistry.All
            .Select(k => (k.KindId, Attach: k.Attach.ToString()))
            .OrderBy(k => k.KindId, StringComparer.Ordinal)
            .ToList();
        var lifecycleSet = new HashSet<string>(AtomTriggers.Lifecycle, StringComparer.Ordinal);
        var triggers = AtomTriggers.All
            .Select(t => (Id: t, Authorable: !lifecycleSet.Contains(t)))
            .OrderBy(t => t.Id, StringComparer.Ordinal)
            .ToList();
        return new AtomVocabMirror(attachPoints, kinds, triggers);
    }

    public static MismatchReport Run(AtomVocabMirror mirror)
    {
        var live = LiveVocab();
        var mismatches = new List<string>();

        if (live.AttachPoints.Count != mirror.AttachPoints.Count)
            mismatches.Add($"live has {live.AttachPoints.Count} attach point(s), mirror has {mirror.AttachPoints.Count}");
        var liveAttach = new HashSet<string>(live.AttachPoints, StringComparer.Ordinal);
        var mirrorAttach = new HashSet<string>(mirror.AttachPoints, StringComparer.Ordinal);
        foreach (var a in liveAttach) if (!mirrorAttach.Contains(a)) mismatches.Add($"attach point '{a}' missing from mirror");
        foreach (var a in mirrorAttach) if (!liveAttach.Contains(a)) mismatches.Add($"mirror attach point '{a}' does not exist live");

        if (live.Kinds.Count != mirror.Kinds.Count)
            mismatches.Add($"live has {live.Kinds.Count} kind(s), mirror has {mirror.Kinds.Count}");
        var liveKinds = live.Kinds.ToDictionary(k => k.Id, k => k.Attach, StringComparer.Ordinal);
        var mirrorKinds = mirror.Kinds.ToDictionary(k => k.Id, k => k.Attach, StringComparer.Ordinal);
        foreach (var (id, attach) in live.Kinds)
        {
            if (!mirrorKinds.TryGetValue(id, out var mirrorAttachName))
            { mismatches.Add($"kind '{id}' missing from mirror"); continue; }
            if (!string.Equals(mirrorAttachName, attach, StringComparison.Ordinal))
                mismatches.Add($"kind '{id}': mirror attach '{mirrorAttachName}' != live '{attach}'");
        }
        foreach (var (id, _) in mirror.Kinds)
            if (!liveKinds.ContainsKey(id))
                mismatches.Add($"mirror kind '{id}' does not exist live — stale entry");

        if (live.Triggers.Count != mirror.Triggers.Count)
            mismatches.Add($"live has {live.Triggers.Count} trigger(s), mirror has {mirror.Triggers.Count}");
        var liveTrig = live.Triggers.ToDictionary(t => t.Id, t => t.Authorable, StringComparer.Ordinal);
        var mirrorTrig = mirror.Triggers.ToDictionary(t => t.Id, t => t.Authorable, StringComparer.Ordinal);
        foreach (var (id, authorable) in live.Triggers)
        {
            if (!mirrorTrig.TryGetValue(id, out var mirrorAuthorable))
            { mismatches.Add($"trigger '{id}' missing from mirror"); continue; }
            if (mirrorAuthorable != authorable)
                mismatches.Add($"trigger '{id}': mirror authorable={mirrorAuthorable} != live={authorable}");
        }
        foreach (var (id, _) in mirror.Triggers)
            if (!liveTrig.ContainsKey(id))
                mismatches.Add($"mirror trigger '{id}' does not exist live — stale entry");

        return new MismatchReport(mismatches);
    }

    public static string GenerateJson(AtomVocabMirror v)
    {
        var w = new System.Text.StringBuilder();
        w.AppendLine("{");
        w.AppendLine("  \"schemaVersion\": 1,");
        w.AppendLine("  \"_meta\": {");
        w.AppendLine("    \"note\": \"Generated by tools/PassiveTreeRosterGen --atom-vocab-emit from AttachPoint/AtomKindRegistry/AtomTriggers. Do not hand-edit -- run --atom-vocab-check to detect drift, --atom-vocab-emit to regenerate.\"");
        w.AppendLine("  },");

        w.AppendLine("  \"attachPoints\": [");
        for (var i = 0; i < v.AttachPoints.Count; i++)
            w.AppendLine($"    \"{v.AttachPoints[i]}\"{(i < v.AttachPoints.Count - 1 ? "," : "")}");
        w.AppendLine("  ],");

        w.AppendLine("  \"kinds\": [");
        for (var i = 0; i < v.Kinds.Count; i++)
        {
            var (id, attach) = v.Kinds[i];
            w.AppendLine("    {");
            w.AppendLine($"      \"id\": \"{id}\",");
            w.AppendLine($"      \"attach\": \"{attach}\"");
            w.AppendLine($"    }}{(i < v.Kinds.Count - 1 ? "," : "")}");
        }
        w.AppendLine("  ],");

        w.AppendLine("  \"triggers\": [");
        for (var i = 0; i < v.Triggers.Count; i++)
        {
            var (id, authorable) = v.Triggers[i];
            w.AppendLine("    {");
            w.AppendLine($"      \"id\": \"{id}\",");
            w.AppendLine($"      \"authorable\": {(authorable ? "true" : "false")}");
            w.AppendLine($"    }}{(i < v.Triggers.Count - 1 ? "," : "")}");
        }
        w.AppendLine("  ]");
        w.AppendLine("}");
        return w.ToString();
    }
}
