using FusionRpg.Core.Status;

namespace FusionRpg.Tools.PassiveTreeRosterGen;

public sealed record StatusRosterRow(string Id, string Category, int Ordinal);

/// <summary>
/// Whether `data/seed/statuses/roster.json` still agrees with the shipped
/// <see cref="StatusCategoryRegistry"/> (task A3, spec-tree-plan.md §6/§9/§Reproducibility) — the
/// mirror `tree-plan` reads so its property vocabulary never types "21" by hand. Same `--check`/
/// `--emit` contract as `tools/ElementEnumGen`: the mirror is generated FROM the live registry, and
/// `--status-check` fails on drift rather than silently trusting a stale file.
/// </summary>
public static class StatusRosterCheck
{
    /// <summary>Read live, never typed — the count IS <see cref="StatusCategoryRegistry.AllStatusIds"/>'s
    /// own count, not a literal 21 anywhere in this file.</summary>
    public static IReadOnlyList<StatusRosterRow> LiveRows()
    {
        var ids = StatusCategoryRegistry.AllStatusIds.OrderBy(id => id, StringComparer.Ordinal).ToList();
        var rows = new List<StatusRosterRow>(ids.Count);
        for (var i = 0; i < ids.Count; i++)
            rows.Add(new StatusRosterRow(ids[i], StatusCategoryRegistry.GetRequiredCategory(ids[i]), i));
        return rows;
    }

    public static MismatchReport Run(IReadOnlyList<StatusRosterRow> mirror)
    {
        var live = LiveRows();
        var mismatches = new List<string>();

        if (live.Count != mirror.Count)
            mismatches.Add($"live registry has {live.Count} status(es), mirror has {mirror.Count}");

        var liveById = live.ToDictionary(r => r.Id, StringComparer.Ordinal);
        var mirrorById = mirror.ToDictionary(r => r.Id, StringComparer.Ordinal);

        foreach (var row in live)
        {
            if (!mirrorById.TryGetValue(row.Id, out var mirrorRow))
            {
                mismatches.Add($"live status '{row.Id}' is missing from the mirror");
                continue;
            }
            if (!string.Equals(mirrorRow.Category, row.Category, StringComparison.Ordinal))
                mismatches.Add($"status '{row.Id}': mirror category '{mirrorRow.Category}' != live '{row.Category}'");
        }

        foreach (var row in mirror)
            if (!liveById.ContainsKey(row.Id))
                mismatches.Add($"mirror status '{row.Id}' does not exist in the live registry — stale entry");

        return new MismatchReport(mismatches);
    }

    public static string GenerateJson(IReadOnlyList<StatusRosterRow> rows)
    {
        var w = new System.Text.StringBuilder();
        w.AppendLine("{");
        w.AppendLine("  \"schemaVersion\": 1,");
        w.AppendLine("  \"kind\": \"status\",");
        w.AppendLine("  \"_meta\": {");
        w.AppendLine("    \"note\": \"Generated by tools/PassiveTreeRosterGen --status-emit from StatusCategoryRegistry. Do not hand-edit -- run --status-check to detect drift, --status-emit to regenerate.\"");
        w.AppendLine("  },");
        w.AppendLine("  \"entries\": [");
        for (var i = 0; i < rows.Count; i++)
        {
            var r = rows[i];
            var comma = i < rows.Count - 1 ? "," : "";
            w.AppendLine("    {");
            w.AppendLine($"      \"id\": \"{r.Id}\",");
            w.AppendLine($"      \"category\": \"{r.Category}\",");
            w.AppendLine($"      \"ordinal\": {r.Ordinal}");
            w.AppendLine($"    }}{comma}");
        }
        w.AppendLine("  ]");
        w.AppendLine("}");
        return w.ToString();
    }
}
