"""Tests for item module 13, `set-charm-gen` (docs/architecture/item/spec-set-charm-gen.md).

    python -m pytest tools/seedsmith/tests/test_set_charm_gen.py -q

⭐ **Almost every assertion here runs against the REAL shipped corpus**, not a synthetic fixture:
the 98 affix families, the 30 legacy sets, the 70 charm rows, `core.v1.json` v2, the 84 published
demon themes and the 840-species anchor index. That is deliberate and it is what caught the two
defects this module reports — a vocabulary counted from a fixture proves nothing about whether the
design conclusion drawn from it still holds.

Where a count is a moving target (the demon corpus is being regenerated by another stream while
this runs), the test asserts the RELATIONSHIP rather than the number — `themes < species`, not
`themes == 84` — and the exact figures live in the module's todo entry, dated.
"""
from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from seedsmith.adapters.items.charmgen import rules as charm_rules  # noqa: E402
from seedsmith.adapters.items.registries import load_theme_keys  # noqa: E402
from seedsmith.adapters.items.setgen import brief as brief_mod  # noqa: E402
from seedsmith.adapters.items.setgen import (  # noqa: E402
    cells, dedup, distribute, emit, roles, run as run_mod,
)
from seedsmith.adapters.items.setgen import schema as schema_mod  # noqa: E402
from seedsmith.adapters.items.setgen import themes as themes_mod  # noqa: E402
from seedsmith.adapters.items.setgen import tuning as tuning_mod  # noqa: E402
from seedsmith.adapters.items.setgen import vocab as vocab_mod  # noqa: E402
from seedsmith.adapters.items.setgen.verdict import (  # noqa: E402
    GATING_METRICS,
    REPORT_ONLY_METRICS,
    RunReport,
    Verdict,
    missing_thresholds,
)
from seedsmith.corpus import Corpus  # noqa: E402
from seedsmith.metrics import Ctx, MetricRegistry, Severity, run_all  # noqa: E402
from seedsmith.metrics.cell_occupancy import PROMOTION_TRIGGER, CellOccupancy  # noqa: E402
from seedsmith.metrics.dedup import (  # noqa: E402
    jaccard_estimate,
    minhash_signature,
    shingles,
)
from seedsmith.pipeline.model import BLOCKED_FIELD, Pipeline, audit_schema  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[3]
ITEMS_ROOT = REPO_ROOT / "data" / "seed" / "items"
REGISTRY_DIR = ITEMS_ROOT / "_registry"
SETS_DIR = ITEMS_ROOT / "sets"
CHARMS_DIR = ITEMS_ROOT / "charms"

TUNING = tuning_mod.load()
VOCAB = vocab_mod.build(TUNING)


def _entries(directory: Path, kind: str) -> "list[dict]":
    out: "list[dict]" = []
    for path in sorted(directory.glob("*.json")):
        doc = json.loads(path.read_text(encoding="utf-8"))
        if doc.get("kind") != kind:
            continue
        out.extend(doc.get("entries", []))
    return out


SHIPPED_SETS = _entries(SETS_DIR, "set")
SHIPPED_CHARM_ROWS = _entries(CHARMS_DIR, "charm")
AUTHORED_CHARMS = [c for c in SHIPPED_CHARM_ROWS if not c["id"].startswith("charm.res-")]
RESONANCE_ROWS = [c for c in SHIPPED_CHARM_ROWS if c["id"].startswith("charm.res-")]


# --------------------------------------------------------------------------------------------
# P1 — the model writes identity, deterministic code writes magnitude
# --------------------------------------------------------------------------------------------
class SchemaTests(unittest.TestCase):
    def test_the_schema_is_audit_schema_clean(self) -> None:
        for name, schema in (("set", schema_mod.set_schema(TUNING)),
                             ("charm", schema_mod.charm_schema(TUNING))):
            with self.subTest(schema=name):
                self.assertEqual(audit_schema(schema), [])

    def test_pieces_is_a_closed_enum_and_not_a_bare_integer(self) -> None:
        node = schema_mod.threshold_pieces(TUNING)
        self.assertEqual(node["type"], "integer")
        self.assertEqual(node["enum"], list(TUNING.legal_threshold_pieces))
        # An enum of numbers is a vocabulary, so audit_schema allows it; the SAME node without the
        # enum is exactly what it refuses.
        self.assertEqual(audit_schema({"type": "object", "properties": {
            BLOCKED_FIELD: {"type": "string"}, "pieces": node}}), [])
        bare = audit_schema({"type": "object", "properties": {
            BLOCKED_FIELD: {"type": "string"}, "pieces": {"type": "integer"}}})
        self.assertTrue(bare)

    def test_a_bare_integer_magnitude_field_fails_pipeline_construction(self) -> None:
        broken = schema_mod.set_schema(TUNING)
        broken["properties"]["strength"] = {"type": "integer"}
        with self.assertRaises(ValueError) as caught:
            Pipeline(metric="set-charm-gen", scope="test", schema=broken,
                     gate=lambda _: [], on_persist=lambda _k, _v: None)
        self.assertIn("magnitudes come from", str(caught.exception))

    def test_blocked_is_a_legal_answer_and_writes_nothing(self) -> None:
        written: "list[tuple[str, dict]]" = []
        pipeline = Pipeline(metric="set-charm-gen", scope="test",
                            schema=schema_mod.set_schema(TUNING), gate=lambda _: [],
                            on_persist=lambda k, v: written.append((k, v)))
        self.assertIn(BLOCKED_FIELD, pipeline.schema["properties"])
        self.assertEqual(written, [])

    def test_the_schema_names_no_magnitude_field(self) -> None:
        """`tier` and `cost` are on `audit_schema`'s deny-list by NAME, whatever their type. The
        schema avoids them rather than allow-listing past them — a charm's AP cost is derived from
        its class, and tiers come from `numerics`."""
        text = json.dumps([schema_mod.set_schema(TUNING), schema_mod.charm_schema(TUNING)])
        for banned in ('"tier"', '"cost"', '"apCost"', '"powerBand"'):
            with self.subTest(field=banned):
                self.assertNotIn(f"{banned}:", text)


# --------------------------------------------------------------------------------------------
# The twelve-role cap, applied BEFORE the call
# --------------------------------------------------------------------------------------------
class RoleCapTests(unittest.TestCase):
    def test_the_twelve_sum_to_800_permille_against_the_registry(self) -> None:
        self.assertEqual(roles.assert_core_agrees(), roles.HYBRID_CORE_BUDGET_MILLI)
        self.assertEqual(len(roles.HYBRID_CORE_ROLES), 12)

    def test_every_generated_member_role_is_in_the_twelve(self) -> None:
        """The cap is in the SCHEMA, so the model is never offered an illegal role."""
        enum = schema_mod.set_schema(TUNING)["properties"]["members"]["items"]["properties"]["role"]["enum"]
        self.assertEqual(enum, list(roles.HYBRID_CORE_ROLES))

    def test_a_generated_set_never_claims_head_guard_sense_or_ward_array(self) -> None:
        for role in ("head-guard", "sense", "ward-array"):
            with self.subTest(role=role):
                self.assertNotIn(role, roles.HYBRID_CORE_ROLES)
                problems = roles.refuse_roles(["core-guard", role])
                self.assertTrue(any("SetRoleNotUniversal" in p for p in problems))

    def test_no_set_claims_both_armament_roles(self) -> None:
        problems = roles.refuse_roles(["armament-primary", "armament-secondary", "footing"])
        self.assertTrue(any("SetRoleForbidden" in p for p in problems))
        self.assertEqual(roles.refuse_roles(["armament-primary", "footing"]), [])

    def test_a_role_table_that_moved_raises_instead_of_being_absorbed(self) -> None:
        moved = json.loads((REGISTRY_DIR / "core.v1.json").read_text(encoding="utf-8"))
        for row in moved["roles"]["list"]:
            if row["roleId"] == "footing":
                row["budgetWeightMilli"] = row["budgetWeightMilli"] + 5
        tmp = Path(self.enterContext(__import__("tempfile").TemporaryDirectory())) / "core.json"
        tmp.write_text(json.dumps(moved), encoding="utf-8")
        with self.assertRaises(roles.RoleCapViolation):
            roles.assert_core_agrees(tmp)


# --------------------------------------------------------------------------------------------
# The vocabularies, counted from the live corpus
# --------------------------------------------------------------------------------------------
class VocabularyTests(unittest.TestCase):
    def test_the_capability_vocabulary_is_60_picks_and_the_stat_vocabulary_is_242(self) -> None:
        """Both counted from `data/seed/items/affix-families/*.json`, not transcribed. The spec's
        own arithmetic: 39 element-free + 3x7 variant = 60; 2 + 31x7 + 23 stat.modify = 242."""
        self.assertEqual(VOCAB.capability_count, 60)
        self.assertEqual(VOCAB.stat_count, 242)

    def test_the_pick_counts_are_reproduced_from_the_families_rather_than_asserted(self) -> None:
        families = vocab_mod.load_families()
        self.assertEqual(len(families), 98)
        caps = [f for f in families if f["kindId"] in TUNING.capability_kinds]
        stats = [f for f in families if f["kindId"] in TUNING.stat_kinds]
        self.assertEqual(len(caps), 42)
        self.assertEqual(len(stats), 56)
        variant = [f for f in caps
                   if (f.get("variants") or {}).get("generate") == TUNING.variant_generator]
        self.assertEqual(len(variant), 3)
        self.assertEqual(len(caps) - len(variant) + len(variant) * TUNING.variant_expansion, 60)

    def test_a_family_whose_kind_is_neither_capability_nor_stat_is_refused_not_dropped(self) -> None:
        with self.assertRaises(ValueError) as caught:
            vocab_mod.build(TUNING, directory=self._one_family_dir("atom.invented", "widget.kind"))
        self.assertIn("classify it before generating", str(caught.exception))

    def test_capability_families_carry_roles_and_that_narrows_the_legal_pool(self) -> None:
        """Mitigation #2 in the spec, and the thing that stops the picker collapsing onto the
        three or four most flattering capabilities.

        ⛔ **Measured, and it does NOT hold uniformly.** Every one of the 60 capability picks
        carries a `roles` list (none is unrestricted), and the narrowing is real for most roles —
        `retinue` reaches 7 of 60, `footing` 13. But **`jewel-minor-a` reaches all 60**: it is the
        universal capability host in the shipped corpus, so a set that claims a minor jewel gets
        the whole pool back and mitigation #2 does no work for it. The first draft of this test
        assumed narrowing everywhere and failed; corrected against the data rather than the data
        being read as wrong."""
        self.assertEqual(sum(1 for p in VOCAB.capability if not p.roles), 0)
        self.assertLess(len(VOCAB.capability_for_roles(["retinue"])), VOCAB.capability_count)
        self.assertLess(len(VOCAB.capability_for_roles(["footing"])), VOCAB.capability_count)
        self.assertEqual(len(VOCAB.capability_for_roles(["jewel-minor-a"])),
                         VOCAB.capability_count)

    def _one_family_dir(self, family_id: str, kind_id: str) -> Path:
        tmp = Path(self.enterContext(__import__("tempfile").TemporaryDirectory()))
        (tmp / "x.json").write_text(json.dumps({
            "kind": "affix-family",
            "entries": [{"id": family_id, "kindId": kind_id, "powerBand": "low"}],
        }), encoding="utf-8")
        return tmp


# --------------------------------------------------------------------------------------------
# Atom effect distribution — the capability this module claims
# --------------------------------------------------------------------------------------------
def _pick(family: str, kind_id: str, *, roles_=()) -> vocab_mod.FamilyPick:
    return vocab_mod.FamilyPick(family=family, kind_id=kind_id, variant=None,
                                roles=tuple(roles_), frames=(), power_band="low")


CAPABILITY = _pick("atom.econ-muster", "resource.economy")
STAT_A = _pick("atom.might", "stat.modify")
STAT_B = _pick("atom.vitality", "stat.modify")


class DistributionTests(unittest.TestCase):
    members = ("armament-primary", "core-guard", "footing", "mantle")

    def _plan(self, **over):
        kwargs = dict(member_roles=self.members, capability=CAPABILITY,
                      stats_by_threshold={4: (STAT_A, STAT_B)}, tuning=TUNING, vocabulary=VOCAB)
        kwargs.update(over)
        return distribute.distribute_set(**kwargs)

    def test_exactly_one_capability_atom_and_it_sits_at_the_lowest_threshold(self) -> None:
        plan = self._plan()
        self.assertEqual(plan.problems, [])
        lowest = plan.thresholds[0]
        self.assertEqual(lowest.pieces, TUNING.mandatory_threshold_pieces)
        self.assertIs(lowest.capability, CAPABILITY)
        self.assertEqual([t.capability for t in plan.thresholds[1:]], [None])
        self.assertEqual(lowest.stats, ())

    def test_every_set_has_a_threshold_at_two(self) -> None:
        for count in (2, 3, 4, 6):
            with self.subTest(members=count):
                ladder = distribute.threshold_ladder(TUNING, count)
                self.assertEqual(ladder[0], 2)

    def test_a_grand_set_carries_two_and_four_so_a_partial_grand_set_is_playable(self) -> None:
        self.assertEqual(distribute.threshold_ladder(TUNING, 6), (2, 4, 6))

    def test_no_set_tier_carries_a_More_op_modifier(self) -> None:
        for family in sorted(distribute.MORE_OP_FAMILIES):
            with self.subTest(family=family):
                plan = self._plan(stats_by_threshold={4: (_pick(family, "stat.modify"),)})
                self.assertTrue(any("More-op modifier" in p for p in plan.problems))

    def test_a_capability_at_a_higher_threshold_is_refused(self) -> None:
        plan = self._plan(stats_by_threshold={4: (_pick("atom.venomous", "status.apply"),)})
        self.assertTrue(any("SetTierForbiddenAtom" in p for p in plan.problems))

    def test_a_stat_family_on_the_lowest_threshold_is_refused(self) -> None:
        plan = self._plan(stats_by_threshold={2: (STAT_A,), 4: (STAT_B,)})
        self.assertTrue(any("carries the capability" in p for p in plan.problems))

    def test_a_sets_total_tier_value_never_exceeds_one_and_a_half_AE_per_member(self) -> None:
        plan = self._plan()
        budget = TUNING.set_budget_milli(len(self.members))
        self.assertEqual(budget, 6000)
        self.assertLessEqual(plan.total_value_milli, budget)
        # The apportionment is integer-exact and spends the budget, never a milli over it.
        self.assertEqual(plan.total_value_milli, budget)

    def test_the_budget_is_integer_permille_and_widens_before_multiplying(self) -> None:
        """`long`-equivalent discipline in Python: the multiply happens before the divide, once."""
        self.assertEqual(TUNING.set_budget_milli(6), TUNING.ae_per_member_milli * 6)
        self.assertIsInstance(TUNING.set_budget_milli(6), int)

    def test_a_set_with_no_capability_is_refused(self) -> None:
        plan = self._plan(capability=None)
        self.assertTrue(any("SetCapabilityMissing" in p for p in plan.problems))

    def test_a_set_piece_emits_two_fixed_atoms_and_two_rolls_over_a_two_tier_window(self) -> None:
        roll = distribute.roll_plan(TUNING, min_tier=2)
        self.assertEqual(roll.fixed_atoms, 2)
        self.assertEqual(roll.pool_rolls, 2)
        self.assertEqual((roll.min_tier, roll.max_tier), (2, 3))

    def test_no_set_piece_is_fixed_like_a_unique_or_rolled_like_a_rare(self) -> None:
        """Both named failure modes are refused BY THE PARSER, so no run can be configured into
        them (ssot-sets §3.9)."""
        raw = json.loads((REPO_ROOT / "data" / "tuning" / "set-charm-gen.v1.json")
                         .read_text(encoding="utf-8"))
        unique_like = json.loads(json.dumps(raw))
        unique_like["piece"]["fixedIdentityAtoms"] = 0
        rare_like = json.loads(json.dumps(raw))
        rare_like["piece"]["prefixRolls"] = 2
        rare_like["piece"]["suffixRolls"] = 2
        for label, doc, needle in (("fixed like a unique", unique_like, "fixed like a unique"),
                                   ("rolled like a rare", rare_like, "rolled like a rare")):
            with self.subTest(case=label):
                tmp = Path(self.enterContext(
                    __import__("tempfile").TemporaryDirectory())) / "t.json"
                tmp.write_text(json.dumps(doc), encoding="utf-8")
                with self.assertRaises(tuning_mod.SetCharmTuningError) as caught:
                    tuning_mod.load(tmp)
                self.assertIn(needle, str(caught.exception))

    def test_a_capability_off_every_claimed_role_is_refused(self) -> None:
        plan = self._plan(capability=_pick("atom.terraforming", "grid.spawn",
                                           roles_=("retinue", "jewel-major")))
        self.assertTrue(any("SetCapabilityOffRole" in p for p in plan.problems))


# --------------------------------------------------------------------------------------------
# The distinctness gate — the cell, not the capability
# --------------------------------------------------------------------------------------------
class CellOccupancyTests(unittest.TestCase):
    def test_the_median_cell_occupancy_over_capability_plus_higher_thresholds_is_at_most_two(self) -> None:
        report = cells.cell_report(SHIPPED_SETS)
        self.assertGreater(report.cells, 0)
        self.assertLessEqual(report.median, TUNING.median_cell_occupancy_max)

    def test_the_cell_key_is_the_capability_plus_the_higher_threshold_multiset(self) -> None:
        entry = {"thresholds": [
            {"pieces": 2, "capability": {"family": "atom.econ-muster"}},
            {"pieces": 3, "atoms": [{"family": "atom.might"}]},
            {"pieces": 4, "atoms": [{"family": "atom.vitality"}, {"family": "atom.ferocity"}]},
        ]}
        self.assertEqual(cells.cell_key(entry),
                         ("atom.econ-muster", ("atom.ferocity", "atom.might", "atom.vitality")))

    def test_two_sets_with_the_same_capability_but_different_stats_are_different_cells(self) -> None:
        """This is the whole argument: the capability is the coarse axis. Keyed on it alone these
        two collide; keyed on the cell they do not."""
        base = {"thresholds": [{"pieces": 2, "capability": {"family": "atom.x"}},
                               {"pieces": 4, "atoms": [{"family": "atom.might"}]}]}
        other = {"thresholds": [{"pieces": 2, "capability": {"family": "atom.x"}},
                                {"pieces": 4, "atoms": [{"family": "atom.vitality"}]}]}
        self.assertNotEqual(cells.cell_key(base), cells.cell_key(other))
        self.assertEqual(cells.cell_report([base, other]).cells, 2)

    def test_capability_usage_is_reported_and_does_not_gate(self) -> None:
        findings = self._run_metric()
        usage = [f for f in findings if f.subject == "set:capability-usage"]
        self.assertEqual(len(usage), 1)
        self.assertIs(usage[0].severity, Severity.NOTE)
        self.assertLess(usage[0].evidence["capabilitiesUsed"], VOCAB.capability_count)

    def test_the_metric_reports_median_max_and_singleton_share(self) -> None:
        finding = [f for f in self._run_metric()
                   if f.subject == "set:capability+higher-thresholds"][0]
        for key in ("median", "max", "singletons", "singletonSharePermille", "medianMax"):
            self.assertIn(key, finding.evidence)

    def test_an_empty_set_population_reports_NOT_MEASURED_never_a_pass(self) -> None:
        findings = CellOccupancy().run(Ctx(corpus=Corpus(), adapter=None))
        self.assertEqual([f.severity for f in findings], [Severity.NOT_MEASURED])

    def test_a_median_above_the_ceiling_is_a_GAP(self) -> None:
        clones = [{"thresholds": [{"pieces": 2, "capability": {"family": "atom.x"}},
                                  {"pieces": 4, "atoms": [{"family": "atom.might"}]}]}
                  for _ in range(TUNING.median_cell_occupancy_max + 1)]
        report = cells.cell_report(clones)
        self.assertFalse(report.within(TUNING.median_cell_occupancy_max))

    def test_the_gate_is_unpromoted_and_the_promotion_trigger_is_written_down(self) -> None:
        """⚠ `gates = False` today because the threshold is defined over the GENERATED species-set
        population, which does not exist. The trigger is recorded rather than remembered."""
        self.assertFalse(CellOccupancy.gates)
        self.assertIn("generation run", PROMOTION_TRIGGER)

    def _run_metric(self):
        corpus = Corpus.load(ITEMS_ROOT)
        registry = MetricRegistry()
        registry.register(CellOccupancy())
        return run_all(registry, Ctx(corpus=corpus, adapter=None))


# --------------------------------------------------------------------------------------------
# Ids
# --------------------------------------------------------------------------------------------
class IdTests(unittest.TestCase):
    def test_a_species_set_id_uses_speciesId_never_themeKey(self) -> None:
        self.assertEqual(emit.set_id("allpeater", 1), "set.allpeater-001")
        with self.assertRaises(emit.IdRefused) as caught:
            emit.set_id("demon.allpeater", 1)
        self.assertIn("two dots", str(caught.exception))

    def test_a_tier_container_id_composes_to_one_dot_and_a_zero_padded_suffix(self) -> None:
        set_id = emit.set_id("allpeater", 1)
        self.assertEqual(emit.tier_container_id(set_id, 4), "set.allpeater-001-04")
        self.assertEqual(emit.tier_container_id(set_id, 10), "set.allpeater-001-10")
        self.assertEqual(emit.tier_container_id(set_id, 4).count("."), 1)

    def test_the_zero_pad_makes_tier_ids_sort_ordinally(self) -> None:
        """Module 12 proved the pad is load-bearing at the DAL — `ORDER BY container_id ASC`."""
        set_id = emit.set_id("allpeater", 1)
        ids = [emit.tier_container_id(set_id, n) for n in (10, 2, 4)]
        self.assertEqual(sorted(ids), [emit.tier_container_id(set_id, n) for n in (2, 4, 10)])

    def test_no_generated_id_collides_with_a_legacy_theme_partition(self) -> None:
        partitions = themes_mod.legacy_partition_ids()
        self.assertEqual(len(partitions), 5)
        with self.assertRaises(emit.IdRefused):
            emit.set_id(sorted(partitions)[0], 1, legacy_partitions=partitions)

    def test_the_correction_range_is_never_minted_by_the_generator(self) -> None:
        with self.assertRaises(emit.IdRefused) as caught:
            emit.set_id("allpeater", 900)
        self.assertIn("900-999", str(caught.exception))

    def test_a_build_set_id_keys_on_aptitude_and_archetype(self) -> None:
        self.assertEqual(emit.build_set_id("Might", "offense", 1), "set.might-offense-001")

    def test_every_shipped_species_id_is_kebab_legal_and_mintable(self) -> None:
        partitions = themes_mod.legacy_partition_ids()
        for theme in themes_mod.load_species_themes():
            with self.subTest(species=theme.species_id):
                if theme.species_id in partitions:
                    continue
                minted = emit.set_id(theme.species_id, 1, legacy_partitions=partitions)
                self.assertTrue(emit.CONTAINER_ID_RE.match(minted))


# --------------------------------------------------------------------------------------------
# The theme bridge — one way, and two D34 preconditions that are NOT met
# --------------------------------------------------------------------------------------------
class ThemeBridgeTests(unittest.TestCase):
    def test_no_theme_reaches_generation_at_basis_name(self) -> None:
        """⭐ D34's own test, honestly: `theme-enrich` has NOT run, so the name-basis population is
        not empty — it is HELD. What is asserted is that none of it reaches generation."""
        pool = themes_mod.load_species_themes()
        selected = themes_mod.generatable(pool)
        self.assertTrue(selected)
        self.assertEqual([t.theme_key for t in selected if t.basis == "name"], [])

    def test_the_held_population_is_reported_rather_than_silently_skipped(self) -> None:
        report = themes_mod.holdback_report(themes_mod.load_species_themes())
        self.assertGreater(len(report.held), 0, "theme-enrich (P0.3) has not run yet")
        self.assertIn("basis=name", report.held_by_reason())
        self.assertFalse(report.complete)

    def test_the_theme_registry_covers_every_shipped_species(self) -> None:
        """⛔ It does not, and this test is the record of that — `theme-refresh` (P0.2) is unbuilt.
        Asserted as a RELATIONSHIP, not a number: the demon corpus is being regenerated by another
        stream while this runs, so pinning 84-vs-840 would make this test that stream's problem."""
        coverage = themes_mod.coverage_report(themes_mod.load_species_themes())
        self.assertGreater(coverage.species, coverage.themes)
        self.assertFalse(coverage.complete)
        self.assertGreater(len(coverage.uncovered), 0)

    def test_the_species_count_is_the_index_not_the_file_count(self) -> None:
        """⛔ The defect this module found. `ls data/seed/demons/species/{plant,zombie} | wc -l`
        counts FAMILY files; `_index.json` maps speciesId -> family path and is the species count.
        The two differ by more than a factor of one and a half."""
        species = len(themes_mod.shipped_species_ids())
        families = themes_mod.species_family_file_count()
        self.assertGreater(species, families)

    def test_nothing_generated_keys_on_theme_rarity(self) -> None:
        """§2.4a — `RarityForRank` is proportional in count, so a species moves tier as the roster
        grows without moving rank. Asserted structurally over every generator module."""
        package = Path(themes_mod.__file__).parent
        for path in sorted(package.glob("*.py")):
            source = path.read_text(encoding="utf-8")
            body = "\n".join(line for line in source.splitlines()
                             if not line.strip().startswith("#"))
            with self.subTest(module=path.name):
                self.assertNotIn(".rarity ==", body)
                self.assertNotIn("theme.rarity", body.replace("`theme.rarity`", ""))

    def test_nothing_in_the_generator_writes_the_demons_corpus(self) -> None:
        """The one-way bridge, asserted structurally rather than promised."""
        for package in ("setgen", "charmgen"):
            base = Path(themes_mod.__file__).parent.parent / package
            for path in sorted(base.glob("*.py")):
                source = path.read_text(encoding="utf-8")
                with self.subTest(module=f"{package}/{path.name}"):
                    for verb in ("write_text", "open(", "mkdir"):
                        for line in source.splitlines():
                            if verb in line and "demons" in line:
                                self.fail(f"{path.name} may write the demons corpus: {line.strip()}")

    def test_a_build_set_has_a_legal_themeKey(self) -> None:
        keys = load_theme_keys()
        build = themes_mod.load_build_themes()
        self.assertEqual(len(build), 36)
        for theme in build:
            with self.subTest(theme=theme.theme_key):
                self.assertIn(theme.theme_key, keys)

    def test_the_build_population_is_twelve_aptitudes_times_three_archetypes(self) -> None:
        roster = json.loads((REPO_ROOT / "data" / "seed" / "aptitudes" / "roster.json")
                            .read_text(encoding="utf-8"))
        aptitudes = {r["id"] for r in roster["entries"]}
        build = themes_mod.load_build_themes()
        self.assertEqual({t.aptitude for t in build}, aptitudes)
        self.assertEqual({t.archetype for t in build}, set(TUNING.archetypes))
        self.assertEqual(len(build), len(aptitudes) * len(TUNING.archetypes))

    def test_the_three_theme_populations_cannot_collide(self) -> None:
        legacy = {f"theme.{t}" for t in themes_mod.legacy_theme_ids()}
        build = themes_mod.build_theme_keys()
        demon = {t.theme_key for t in themes_mod.load_species_themes()}
        self.assertEqual(legacy & build, set())
        self.assertEqual(legacy & demon, set())
        self.assertEqual(build & demon, set())


# --------------------------------------------------------------------------------------------
# Charms
# --------------------------------------------------------------------------------------------
class CharmTests(unittest.TestCase):
    def test_the_authored_charm_split_is_21_32_7_excluding_the_ten_resonance_rows(self) -> None:
        self.assertEqual(len(SHIPPED_CHARM_ROWS), 70)
        self.assertEqual(len(RESONANCE_ROWS), 10)
        self.assertEqual(len(AUTHORED_CHARMS), 60)
        split = {c: sum(1 for e in AUTHORED_CHARMS if e["charmClass"] == c)
                 for c in ("minor", "standard", "signet")}
        self.assertEqual(split, {"minor": 21, "standard": 32, "signet": 7})

    def test_the_charm_axis_gini_does_not_exceed_the_authored_corpus_value(self) -> None:
        gini = charm_rules.axis_gini_permille([c["axis"] for c in AUTHORED_CHARMS])
        self.assertEqual(gini, TUNING.charm_axis_gini_max_permille)
        self.assertLessEqual(gini, TUNING.charm_axis_gini_max_permille)

    def test_a_generated_population_may_flatten_the_skew_but_never_deepen_it(self) -> None:
        flatter = charm_rules.axis_gini_permille(list(charm_rules.CHARM_AXES) * 4)
        self.assertLess(flatter, TUNING.charm_axis_gini_max_permille)
        deeper = charm_rules.axis_gini_permille(["economy"] * 40 + ["offense"] * 2)
        self.assertGreater(deeper, TUNING.charm_axis_gini_max_permille)

    def test_no_charm_carries_Increased_or_More(self) -> None:
        for family in sorted(charm_rules.NON_FLAT_FAMILIES):
            with self.subTest(family=family):
                plan = charm_rules.distribute_charm(
                    charm_class="standard", axis="offense",
                    families=(_pick(family, "stat.modify"),), drawback=None, tuning=TUNING)
                self.assertTrue(any("CharmForbiddenOp" in p for p in plan.problems))
        self.assertEqual(TUNING.charm_legal_ops, ("Flat",))

    def test_no_family_appears_on_both_a_jewel_minor_base_and_a_charm(self) -> None:
        jewel = charm_rules.families_on_jewel_minor(VOCAB.stat + VOCAB.capability)
        self.assertTrue(jewel, "the corpus does make families legal on jewel-minor roles")
        offender = sorted(jewel)[0]
        plan = charm_rules.distribute_charm(
            charm_class="standard", axis="offense",
            families=(_pick(offender, "stat.modify"),), drawback=None, tuning=TUNING,
            jewel_minor_families=jewel)
        self.assertTrue(any("CharmFamilyOnJewelMinor" in p for p in plan.problems))

    def test_a_signet_rolls_nothing_is_unique_carry_and_carries_a_drawback(self) -> None:
        rule = TUNING.charm_class("signet")
        self.assertEqual((rule.max_pool_rolls, rule.unique_carry, rule.requires_drawback),
                         (0, True, True))
        no_drawback = charm_rules.distribute_charm(
            charm_class="signet", axis="offense", families=(STAT_A,), drawback=None, tuning=TUNING)
        self.assertTrue(any("CharmSignetHasNoDrawback" in p for p in no_drawback.problems))
        ok = charm_rules.distribute_charm(
            charm_class="signet", axis="offense", families=(STAT_A,),
            drawback=_pick("atom.frailty", "stat.modify"), tuning=TUNING)
        self.assertEqual(ok.problems, [])
        self.assertEqual(ok.pool_rolls, 0)

    def test_the_shipped_signets_already_satisfy_the_three_class_rules(self) -> None:
        signets = [c for c in AUTHORED_CHARMS if c["charmClass"] == "signet"]
        self.assertEqual(len(signets), 7)
        for entry in signets:
            with self.subTest(charm=entry["id"]):
                self.assertEqual(entry.get("prefixRolls", 0) + entry.get("suffixRolls", 0), 0)
                self.assertTrue(entry.get("uniqueCarry"))

    def test_apCost_is_derived_from_the_class_and_never_asked_of_the_model(self) -> None:
        self.assertNotIn("apCost", schema_mod.charm_schema(TUNING)["properties"])
        self.assertEqual(TUNING.charm_class("minor").ap_cost, 1)
        self.assertEqual(TUNING.charm_class("signet").ap_cost, 5)

    def test_a_charm_sits_at_most_one_band_below_an_equip_container(self) -> None:
        too_high = charm_rules.distribute_charm(
            charm_class="standard", axis="offense", families=(STAT_A,), drawback=None,
            tuning=TUNING, equip_max_tier=5, charm_max_tier=5)
        self.assertTrue(any("CharmTierTooHigh" in p for p in too_high.problems))
        ok = charm_rules.distribute_charm(
            charm_class="standard", axis="offense", families=(STAT_A,), drawback=None,
            tuning=TUNING, equip_max_tier=5, charm_max_tier=4)
        self.assertEqual(ok.problems, [])


# --------------------------------------------------------------------------------------------
# Name distinctness — measured exactly, because the shared metric's estimate is not
# --------------------------------------------------------------------------------------------
SET_CHARM_NAMES = {e["id"]: e["name"] for e in SHIPPED_SETS + SHIPPED_CHARM_ROWS}


class NameDistinctnessTests(unittest.TestCase):
    def test_no_two_generated_entries_share_an_exact_name(self) -> None:
        """Zero tolerance, and the shipped population already meets it."""
        report = dedup.dedup_report(SET_CHARM_NAMES)
        self.assertEqual(report.population, 100)
        self.assertEqual(report.exact_duplicates, ())
        self.assertLessEqual(len(report.exact_duplicates), TUNING.exact_duplicate_names_max)

    def test_the_lexical_near_duplicate_rate_is_at_most_half_a_percent(self) -> None:
        """⚠ **Measured, with the honest caveat.** Over the 100 shipped set + charm rows there is
        exactly **one** genuine near-duplicate pair — `'Root of the Foundation'` /
        `'Signet of the Foundation'`, true Jaccard 0.652 — which is 10 permille, above the 5
        permille ceiling. **At n=100 the ceiling is not measurable**: one pair is already 10
        permille, so the smallest non-zero value the statistic can take is twice the threshold.
        The threshold is derived for the generated population (~1,844 entries, where 5 permille is
        ~9 pairs) and that population does not exist yet.

        What IS asserted here: the exact count, so a second pair appearing is a failure, and that
        the one pair found is genuinely above the similarity threshold rather than an artefact."""
        report = dedup.dedup_report(SET_CHARM_NAMES)
        self.assertEqual(len(report.near_duplicates), 1)
        pair = report.near_duplicates[0]
        self.assertGreaterEqual(pair.jaccard_permille, 600)
        self.assertEqual(report.rate_permille, 10)
        self.assertLess(TUNING.near_duplicate_rate_max_permille, report.rate_permille)

    def test_the_shared_metrics_minhash_estimate_over_reports_on_short_names(self) -> None:
        """⛔ The defect this module found, pinned so the fix has a test waiting for it. The shared
        `SemanticDedup/NearDuplicate` estimates Jaccard from a 32-hash MinHash signature; on names
        this short the estimate is biased upward by up to 7x, and it reports pairs that share
        almost nothing."""
        for left, right in (("Tier Duration", "Husk of the Murmuration"),
                            ("Spiralled Bead", "Spiralled Intercom")):
            with self.subTest(pair=(left, right)):
                true = dedup.exact_jaccard_permille(left, right)
                estimate = jaccard_estimate(minhash_signature(shingles(left)),
                                            minhash_signature(shingles(right)))
                self.assertLess(true, 600, "these are not near-duplicates by exact Jaccard")
                self.assertGreater(estimate, 0.6, "but the shipped estimate says they are")

    def test_the_exact_filter_agrees_with_the_estimate_where_the_pair_is_real(self) -> None:
        """The fix is a filter, not a replacement: LSH is a candidate generator and the exact
        check keeps every genuine pair it proposes."""
        true = dedup.exact_jaccard_permille("Root of the Foundation", "Signet of the Foundation")
        self.assertGreaterEqual(true, 600)


# --------------------------------------------------------------------------------------------
# Verification discipline
# --------------------------------------------------------------------------------------------
class VerdictTests(unittest.TestCase):
    def test_every_gating_metric_named_in_this_spec_has_a_threshold(self) -> None:
        """The meta-test: a command without a threshold is not verification."""
        self.assertEqual(missing_thresholds(TUNING), [])
        self.assertTrue(GATING_METRICS)

    def test_an_unevaluated_partition_reports_NOT_MEASURED_and_the_run_verdict_is_not_pass(self) -> None:
        report = RunReport()
        for metric in GATING_METRICS:
            report.record(metric, ran=True, cleared=True)
        self.assertIs(report.verdict, Verdict.PASS)
        report.held_partitions.append("basis=name (31 themes)")
        self.assertIs(report.verdict, Verdict.NOT_MEASURED)

    def test_a_gate_that_did_not_run_denies_the_pass(self) -> None:
        report = RunReport()
        for index, metric in enumerate(GATING_METRICS):
            report.record(metric, ran=index > 0, cleared=True)
        self.assertIs(report.verdict, Verdict.NOT_MEASURED)

    def test_a_failed_gate_beats_an_unmeasured_one(self) -> None:
        report = RunReport()
        names = list(GATING_METRICS)
        report.record(names[0], ran=True, cleared=False)
        for metric in names[1:]:
            report.record(metric, ran=False, cleared=False)
        self.assertIs(report.verdict, Verdict.FAIL)

    def test_the_report_only_metrics_still_appear_in_the_report(self) -> None:
        """A metric that runs and is never read is the same as one that never ran."""
        self.assertTrue(REPORT_ONLY_METRICS)
        self.assertEqual(set(REPORT_ONLY_METRICS) & set(GATING_METRICS), set())
        self.assertTrue(all(m in RunReport().to_dict()["reportOnly"] for m in REPORT_ONLY_METRICS))


# --------------------------------------------------------------------------------------------
# The run — resume, and the brief
# --------------------------------------------------------------------------------------------
class RunTests(unittest.TestCase):
    def _plan(self, ledger=None, population="build", kind="set"):
        return run_mod.plan_run(kind=kind, population=population, tuning=TUNING,
                                vocabulary=VOCAB, ledger=ledger or {})

    def test_the_build_population_plans_thirty_six_subjects(self) -> None:
        plan = self._plan()
        self.assertEqual(len(plan.subjects), 36)
        self.assertTrue(plan.complete)

    def test_the_species_population_plans_only_the_generatable_themes(self) -> None:
        plan = self._plan(population="species")
        held = themes_mod.holdback_report(themes_mod.load_species_themes())
        self.assertEqual(len(plan.subjects), held.generatable)
        self.assertFalse(plan.complete)

    def test_the_run_resumes_after_an_interrupt_without_duplicating_entries(self) -> None:
        first = self._plan()
        done = {s.subject_id: s.to_dict() for s in first.subjects[:10]}
        resumed = self._plan(ledger=done)
        self.assertEqual(len(resumed.subjects), len(first.subjects) - 10)
        self.assertEqual(len(resumed.already_done), 10)
        self.assertEqual(set(s.subject_id for s in resumed.subjects) & set(done), set())

    def test_re_running_over_unchanged_themes_is_byte_identical(self) -> None:
        a = self._plan()
        b = self._plan()
        self.assertEqual([s.to_dict() for s in a.subjects], [s.to_dict() for s in b.subjects])
        self.assertEqual([s.brief for s in a.subjects], [s.brief for s in b.subjects])

    def test_the_ledger_write_is_atomic(self) -> None:
        tmp = Path(self.enterContext(__import__("tempfile").TemporaryDirectory())) / "l.json"
        run_mod.write_ledger({"a": {"kind": "set"}}, tmp)
        self.assertEqual(run_mod.read_ledger(tmp), {"a": {"kind": "set"}})
        self.assertEqual(list(tmp.parent.glob("*.tmp")), [])

    def test_there_is_no_build_charm_population(self) -> None:
        with self.assertRaises(ValueError):
            self._plan(kind="charm", population="build")

    def test_the_brief_names_only_legal_roles_and_no_number(self) -> None:
        theme = themes_mod.load_build_themes()[0]
        text = brief_mod.build_set_brief(theme, TUNING, VOCAB)
        for dropped in ("head-guard", "sense", "ward-array", "standard"):
            with self.subTest(role=dropped):
                self.assertNotIn(dropped, text)
        for magnitude in ("per-mille", "permille", "AE", "milli"):
            with self.subTest(token=magnitude):
                self.assertNotIn(magnitude, text)

    def test_the_brief_carries_the_themes_own_motifs_inline(self) -> None:
        theme = themes_mod.generatable(themes_mod.load_species_themes())[0]
        text = brief_mod.build_set_brief(theme, TUNING, VOCAB)
        for motif in theme.motifs:
            self.assertIn(motif, text)


# --------------------------------------------------------------------------------------------
# What this module must NOT ask back
# --------------------------------------------------------------------------------------------
class SC7Tests(unittest.TestCase):
    def test_set_eligible_is_never_requested_back_into_the_rarity_budget_registry(self) -> None:
        """Module 7 dropped `set_eligible` and `charm_potency` under SC7 — D15 makes the first
        vacuous (a set has no rarity; it completes from pieces of any rung) and a registered key
        with no shipped consumer rejects at seed load. This module's only obligation is not to ask
        for them back."""
        base = Path(themes_mod.__file__).parent
        for package in (base, base.parent / "charmgen"):
            for path in sorted(package.glob("*.py")):
                text = path.read_text(encoding="utf-8")
                body = "\n".join(l for l in text.splitlines() if not l.strip().startswith("#"))
                with self.subTest(module=f"{package.name}/{path.name}"):
                    self.assertNotIn("set_eligible", body)
                    self.assertNotIn("charm_potency", body)
        tuning_text = (REPO_ROOT / "data" / "tuning" / "set-charm-gen.v1.json").read_text(
            encoding="utf-8")
        self.assertNotIn("setEligible", tuning_text)
        self.assertNotIn("charmPotency", tuning_text)

    def test_the_tuning_file_carries_no_content_ceiling(self) -> None:
        """D17 is a position: the dead tail stays. A `maxGeneratedSets` key would be a hard
        progression ceiling on content breadth."""
        doc = json.loads((REPO_ROOT / "data" / "tuning" / "set-charm-gen.v1.json")
                         .read_text(encoding="utf-8"))
        flat = json.dumps(doc)
        for banned in ("maxGeneratedSets", "maxSpeciesSets", "rosterCap"):
            self.assertNotIn(banned, flat)


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
