"""Tests for item module 4, `sockets-gen` (docs/architecture/item-seedgen/spec-sockets-gen.md).

    python -m pytest tools/seedsmith/tests/test_sockets_gen.py -v

Two kinds of assertion here, deliberately kept apart:

- **Harness-mechanics tests** (`EmitTests`, `SchemaTests`, `BriefPoolTests`, `RunPlanTests`) run
  against an isolated `tmp_path` gems directory and ledger file — they prove `plan`/`resume`/
  `reconcile`/`overwrite`/id-minting work in general, the same way `test_run_ledger.py` proves
  `RunLedger` works in general.
- **Real-corpus tests** (`RealGemsCorpusTests`) run against the actual, committed
  `data/seed/items/gems/*.json` — mirroring `test_set_charm_gen.py`'s own precedent ("almost every
  assertion here runs against the REAL shipped corpus... that is what caught the two defects this
  module reports"). These are what prove the module's own acceptance criterion 2: the
  allocated-but-never-authored `gems/2` partition (confirmed empty by `allocated_partitions.json`
  naming `gems/1,2,3` while only `g1.json`/`g3.json` existed on disk) now has a real, importable
  file, generated by this module's own tool.
"""
from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from seedsmith.adapters.items.gemgen import brief as brief_mod  # noqa: E402
from seedsmith.adapters.items.gemgen import emit  # noqa: E402
from seedsmith.adapters.items.gemgen import run as run_mod  # noqa: E402
from seedsmith.adapters.items.gemgen import schema as schema_mod  # noqa: E402
from seedsmith.pipeline.model import BLOCKED_FIELD, audit_schema  # noqa: E402
from seedsmith.pipeline.run_ledger import RunLedger  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[3]
GEMS_DIR = REPO_ROOT / "data" / "seed" / "items" / "gems"
AFFIX_FAMILIES_DIR = REPO_ROOT / "data" / "seed" / "items" / "affix-families"
SNAPSHOT_PATH = (REPO_ROOT / "tools" / "seedsmith" / "seedsmith" / "adapters" / "items"
                / "_registry_snapshot" / "allocated_partitions.json")


def _real_affix_family_ids() -> "frozenset[str]":
    ids: "set[str]" = set()
    for path in sorted(AFFIX_FAMILIES_DIR.glob("g-*.json")):
        doc = json.loads(path.read_text(encoding="utf-8"))
        for entry in doc.get("entries", []):
            ids.add(entry["id"])
    return frozenset(ids)


def _load_gem_entries(path: Path) -> "list[dict]":
    doc = json.loads(path.read_text(encoding="utf-8"))
    assert doc.get("kind") == "gem"
    return doc.get("entries", [])


REAL_FAMILY_IDS = _real_affix_family_ids()


def _valid_answer(name: str, name_key: str) -> dict:
    return {"name": name, "nameKey": name_key}


# ------------------------------------------------------------------------------------------------
# emit.py — ids, icon keys, the power-band rotation, and the final entry shape
# ------------------------------------------------------------------------------------------------
class EmitTests(unittest.TestCase):
    def test_mint_gem_id_uses_partition_slot_verbatim(self) -> None:
        self.assertEqual(emit.mint_gem_id("gems/2", 14), "gem.g2-014")
        self.assertEqual(emit.mint_gem_id("gems/1", 1), "gem.g1-001")

    def test_mint_gem_id_refuses_out_of_range_seq(self) -> None:
        with self.assertRaises(emit.IdRefused):
            emit.mint_gem_id("gems/2", 0)
        with self.assertRaises(emit.IdRefused):
            emit.mint_gem_id("gems/2", 900)

    def test_mint_gem_id_refuses_a_non_gems_partition(self) -> None:
        with self.assertRaises(emit.IdRefused):
            emit.mint_gem_id("charms/econ", 1)
        with self.assertRaises(emit.IdRefused):
            emit.mint_gem_id("gems/0", 1)

    def test_resolve_power_band_is_a_deterministic_three_step_rotation(self) -> None:
        bands = [emit.resolve_power_band(i) for i in range(6)]
        self.assertEqual(bands, ["medium", "high", "low", "medium", "high", "low"])

    def test_resolve_power_band_refuses_negative_index(self) -> None:
        with self.assertRaises(emit.IdRefused):
            emit.resolve_power_band(-1)

    def test_icon_key_derives_from_name_key(self) -> None:
        self.assertEqual(emit.icon_key("gem.ember-shard"), "icon.gem.ember-shard")

    def test_icon_key_refuses_a_malformed_name_key(self) -> None:
        with self.assertRaises(emit.IdRefused):
            emit.icon_key("not-a-gem-key")

    def test_assemble_entry_field_order_matches_the_shipped_shape(self) -> None:
        entry = emit.assemble_entry(
            entry_id="gem.g2-001", name_key="gem.afflicted-barb", name="Afflicted Barb",
            family_id="atom.affliction", power_band="medium", tags=("offensive",),
        )
        # id, nameKey, name, family, [element], powerBand, [affinityElement], iconKey, tags —
        # entry-shapes.md §1's own example order, with element/affinityElement omitted here since
        # this family has no per-element variant.
        self.assertEqual(list(entry.keys()),
                         ["id", "nameKey", "name", "family", "powerBand", "iconKey", "tags"])
        self.assertEqual(entry["iconKey"], "icon.gem.afflicted-barb")
        self.assertEqual(entry["tags"], ["offensive"])

    def test_assemble_entry_includes_element_and_affinity_when_given(self) -> None:
        entry = emit.assemble_entry(
            entry_id="gem.g1-001", name_key="gem.ember-shard", name="Ember Shard",
            family_id="atom.elemental-power", power_band="medium", tags=("offensive",),
            element="fire", affinity_element="fire",
        )
        self.assertEqual(list(entry.keys()),
                         ["id", "nameKey", "name", "family", "element", "powerBand",
                          "affinityElement", "iconKey", "tags"])

    def test_assemble_entry_refuses_a_family_id_with_no_atom_prefix(self) -> None:
        with self.assertRaises(emit.IdRefused):
            emit.assemble_entry(entry_id="gem.g2-001", name_key="gem.x", name="X",
                                family_id="not-an-atom", power_band="medium", tags=())

    def test_assemble_entry_refuses_a_power_band_outside_the_rotation(self) -> None:
        with self.assertRaises(emit.IdRefused):
            emit.assemble_entry(entry_id="gem.g2-001", name_key="gem.x", name="X",
                                family_id="atom.affliction", power_band="extreme", tags=())

    def test_assemble_entry_refuses_an_empty_name(self) -> None:
        with self.assertRaises(emit.IdRefused):
            emit.assemble_entry(entry_id="gem.g2-001", name_key="gem.x", name="",
                                family_id="atom.affliction", power_band="medium", tags=())


# ------------------------------------------------------------------------------------------------
# schema.py — the model's answer contract, audit_schema-clean
# ------------------------------------------------------------------------------------------------
class SchemaTests(unittest.TestCase):
    def test_the_schema_is_audit_schema_clean_flat_and_elemental(self) -> None:
        for elemental in (False, True):
            with self.subTest(elemental=elemental):
                self.assertEqual(audit_schema(schema_mod.gem_answer_schema(elemental=elemental)), [])

    def test_the_schema_names_no_magnitude_field(self) -> None:
        text = json.dumps([schema_mod.gem_answer_schema(elemental=False),
                           schema_mod.gem_answer_schema(elemental=True)])
        for banned in ('"tier"', '"cost"', '"powerBand"', '"weight"'):
            self.assertNotIn(banned, text)

    def test_validate_answer_accepts_a_well_formed_flat_answer(self) -> None:
        errors = schema_mod.validate_answer(_valid_answer("Afflicted Barb", "gem.afflicted-barb"),
                                            elemental=False)
        self.assertEqual(errors, [])

    def test_validate_answer_rejects_a_bad_name_key(self) -> None:
        errors = schema_mod.validate_answer(_valid_answer("X", "not-a-gem-key"), elemental=False)
        self.assertTrue(errors)

    def test_validate_answer_rejects_an_empty_name(self) -> None:
        errors = schema_mod.validate_answer({"name": "", "nameKey": "gem.x"}, elemental=False)
        self.assertTrue(errors)

    def test_validate_answer_requires_element_when_elemental(self) -> None:
        errors = schema_mod.validate_answer(_valid_answer("Ember Shard", "gem.ember-shard"),
                                            elemental=True)
        self.assertTrue(any("element" in e for e in errors))

    def test_validate_answer_accepts_a_legal_element_when_elemental(self) -> None:
        answer = {"name": "Ember Shard", "nameKey": "gem.ember-shard", "element": "fire"}
        self.assertEqual(schema_mod.validate_answer(answer, elemental=True), [])

    def test_validate_answer_rejects_an_element_when_not_elemental(self) -> None:
        answer = {"name": "X", "nameKey": "gem.x", "element": "fire"}
        errors = schema_mod.validate_answer(answer, elemental=False)
        self.assertTrue(errors)

    def test_validate_answer_blocked_short_circuits_every_other_check(self) -> None:
        errors = schema_mod.validate_answer({BLOCKED_FIELD: "no fitting name", "name": ""},
                                            elemental=False)
        self.assertEqual(errors, [])


# ------------------------------------------------------------------------------------------------
# brief.py — the unauthored-family pool
# ------------------------------------------------------------------------------------------------
class BriefPoolTests(unittest.TestCase):
    def test_unauthored_families_excludes_families_already_claimed_by_a_shipped_gem(self) -> None:
        claimed = brief_mod.used_families()
        pool_ids = {row["id"] for row in brief_mod.unauthored_families(limit=None)}
        self.assertFalse(claimed & pool_ids, "a claimed family must never re-appear in the pool")

    def test_unauthored_families_excludes_elemental_variant_families(self) -> None:
        for row in brief_mod.unauthored_families(limit=None):
            self.assertFalse(brief_mod.is_elemental(row), f"{row['id']} is elemental variant")

    def test_unauthored_families_is_sorted_and_deterministic(self) -> None:
        first = [row["id"] for row in brief_mod.unauthored_families(limit=10)]
        second = [row["id"] for row in brief_mod.unauthored_families(limit=10)]
        self.assertEqual(first, second)
        self.assertEqual(first, sorted(first))

    def test_used_families_reads_the_real_gems_dir_fresh(self) -> None:
        claimed = brief_mod.used_families()
        # g1.json/g3.json ship real families; a fresh read must see them without being told to.
        self.assertIn("atom.might", claimed)
        self.assertIn("atom.bulwark", claimed)

    def test_build_gem_brief_never_offers_a_number_or_a_tag(self) -> None:
        """The brief may (and does) TELL the model it must never pick a tier/power band/tag —
        that instruction text legitimately contains those words, the same way `setgen/brief.py`'s
        own "Never choose a number, a strength, a duration or a tier" does. What must never appear
        is the family's OWN authored tag value leaking into the brief as if it were offered."""
        row = {"id": "atom.affliction", "name": "Affliction", "tags": ["offensive"]}
        text = brief_mod.build_gem_brief(row)
        self.assertNotIn("`tags`", text)
        self.assertNotIn("`powerBand`", text)
        self.assertNotIn("offensive", text)
        self.assertNotIn("defensive", text)

    def test_build_gem_brief_offers_element_only_when_elemental(self) -> None:
        flat = {"id": "atom.affliction", "name": "Affliction"}
        elemental = {"id": "atom.deathblast", "name": "Deathblast",
                    "variants": {"generate": "elements+omni"}}
        self.assertNotIn("`element`", brief_mod.build_gem_brief(flat))
        self.assertIn("`element`", brief_mod.build_gem_brief(elemental))


# ------------------------------------------------------------------------------------------------
# run.py — RunLedger wiring: plan / resume / reconcile / overwrite
# ------------------------------------------------------------------------------------------------
class RunPlanTests(unittest.TestCase):
    def setUp(self) -> None:
        import tempfile
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.tmp_path = Path(self._tmp.name)
        # An empty, isolated "gems dir" -- no family is pre-claimed, so the pool is deterministic
        # and starts at the same three families every test run: atom.affliction, atom.arm-hardening,
        # atom.arm-riveting (confirmed against the real registry in BriefPoolTests above).
        self.gems_dir = self.tmp_path / "gems"
        self.gems_dir.mkdir()
        self.ledger_path = self.tmp_path / "gem-gen.ledger.json"

    def _answer_fn(self, subject: run_mod.Subject) -> dict:
        return _valid_answer(f"Test {subject.family_id}", f"gem.test-{subject.index}")

    def test_plan_partition_batches_and_mints_sequential_ids(self) -> None:
        plan = run_mod.plan_partition("gems/2", batch_size=3, gems_dir=self.gems_dir, ledger={})
        self.assertEqual([s.entry_id for s in plan.subjects],
                         ["gem.g2-001", "gem.g2-002", "gem.g2-003"])
        self.assertEqual([s.family_id for s in plan.subjects],
                         ["atom.affliction", "atom.arm-hardening", "atom.arm-riveting"])
        self.assertEqual(plan.already_done, [])
        self.assertFalse(plan.complete is True and plan.subjects)  # sanity: complete means no work

    def test_generate_partition_resume_produces_nothing_the_second_time(self) -> None:
        produced = run_mod.generate_partition(
            "gems/2", answer_fn=self._answer_fn, batch_size=3,
            ledger_path=self.ledger_path, gems_dir=self.gems_dir)
        self.assertEqual(len(produced), 3)

        produced_again = run_mod.generate_partition(
            "gems/2", answer_fn=self._answer_fn, batch_size=3,
            ledger_path=self.ledger_path, gems_dir=self.gems_dir)
        self.assertEqual(produced_again, {})

        plan = run_mod.plan_partition("gems/2", batch_size=3, gems_dir=self.gems_dir,
                                      ledger=RunLedger(self.ledger_path))
        self.assertEqual(plan.subjects, [])
        self.assertEqual(len(plan.already_done), 3)

    def test_reconcile_recovers_a_corrupted_ledger_row(self) -> None:
        run_mod.generate_partition("gems/2", answer_fn=self._answer_fn, batch_size=3,
                                   ledger_path=self.ledger_path, gems_dir=self.gems_dir)
        doc = json.loads(self.ledger_path.read_text(encoding="utf-8"))
        first_key = "gem-gems/2-atom.affliction"
        self.assertIn(first_key, doc["done"])
        doc["done"][first_key] = {"entryId": "gem.g2-001"}  # no "entry" -- a corrupted row
        self.ledger_path.write_text(json.dumps(doc), encoding="utf-8")

        plan = run_mod.plan_partition("gems/2", batch_size=3, gems_dir=self.gems_dir,
                                      ledger=RunLedger(self.ledger_path))
        self.assertEqual([s.subject_id for s in plan.subjects], [first_key])
        self.assertEqual(len(plan.already_done), 2)
        # And the id it gets reminted is the SAME one it had before -- position-derived, not
        # accidentally shifted by the other two rows still being done.
        self.assertEqual(plan.subjects[0].entry_id, "gem.g2-001")

    def test_overwrite_by_explicit_ids_only_touches_those_subjects(self) -> None:
        run_mod.generate_partition("gems/2", answer_fn=self._answer_fn, batch_size=3,
                                   ledger_path=self.ledger_path, gems_dir=self.gems_dir)
        target_id = "gem-gems/2-atom.arm-hardening"
        produced = run_mod.generate_partition(
            "gems/2", answer_fn=self._answer_fn, batch_size=3, ledger_path=self.ledger_path,
            gems_dir=self.gems_dir, overwrite=[target_id])
        self.assertEqual(list(produced.keys()), [target_id])

    def test_overwrite_all_requires_the_literal_string(self) -> None:
        run_mod.generate_partition("gems/2", answer_fn=self._answer_fn, batch_size=3,
                                   ledger_path=self.ledger_path, gems_dir=self.gems_dir)
        produced = run_mod.generate_partition(
            "gems/2", answer_fn=self._answer_fn, batch_size=3, ledger_path=self.ledger_path,
            gems_dir=self.gems_dir, overwrite="all")
        self.assertEqual(len(produced), 3)

    def test_a_typo_d_overwrite_scope_fails_loudly_not_silently(self) -> None:
        with self.assertRaises(ValueError):
            run_mod.generate_partition(
                "gems/2", answer_fn=self._answer_fn, batch_size=3, ledger_path=self.ledger_path,
                gems_dir=self.gems_dir, overwrite="al")  # a typo of "all", not a list

    def test_apply_answer_raises_blocked_for_a_legal_decline(self) -> None:
        plan = run_mod.plan_partition("gems/2", batch_size=1, gems_dir=self.gems_dir, ledger={})
        subject = plan.subjects[0]
        with self.assertRaises(run_mod.Blocked):
            run_mod.apply_answer(subject, {BLOCKED_FIELD: "no fitting name"})

    def test_apply_answer_raises_value_error_for_a_malformed_answer(self) -> None:
        plan = run_mod.plan_partition("gems/2", batch_size=1, gems_dir=self.gems_dir, ledger={})
        subject = plan.subjects[0]
        with self.assertRaises(ValueError):
            run_mod.apply_answer(subject, {"name": "X", "nameKey": "not-legal"})

    def test_apply_answer_copies_family_tags_and_resolves_power_band_by_position(self) -> None:
        plan = run_mod.plan_partition("gems/2", batch_size=3, gems_dir=self.gems_dir, ledger={})
        entries = [run_mod.apply_answer(s, _valid_answer(f"N{i}", f"gem.n{i}"))
                  for i, s in enumerate(plan.subjects)]
        self.assertEqual([e["powerBand"] for e in entries], ["medium", "high", "low"])
        self.assertEqual(entries[0]["tags"], ["offensive"])       # atom.affliction
        self.assertEqual(entries[1]["tags"], ["defensive"])       # atom.arm-hardening

    def test_write_partition_file_round_trips_the_shipped_shape(self) -> None:
        plan = run_mod.plan_partition("gems/2", batch_size=2, gems_dir=self.gems_dir, ledger={})
        entries = [run_mod.apply_answer(s, _valid_answer(f"N{i}", f"gem.n{i}"))
                  for i, s in enumerate(plan.subjects)]
        target = run_mod.write_partition_file("gems/2", entries,
                                              path=self.tmp_path / "g2.json")
        doc = json.loads(target.read_text(encoding="utf-8"))
        self.assertEqual(doc["schemaVersion"], 1)
        self.assertEqual(doc["kind"], "gem")
        self.assertEqual(doc["_meta"]["partition"], "gems/2")
        self.assertEqual(len(doc["entries"]), 2)
        self.assertEqual(doc["entries"], entries)


# ------------------------------------------------------------------------------------------------
# The real, shipped corpus — this module's own acceptance evidence
# ------------------------------------------------------------------------------------------------
class RealGemsCorpusTests(unittest.TestCase):
    def test_gems_2_partition_was_a_confirmed_content_gap_before_this_module(self) -> None:
        """The audit finding this module exists to close: `allocated_partitions.json` allocates
        `gems/1,2,3`, but only g1/g3 were ever authored."""
        snapshot = json.loads(SNAPSHOT_PATH.read_text(encoding="utf-8"))
        self.assertIn("gems/1", snapshot["partitionKind"])
        self.assertIn("gems/2", snapshot["partitionKind"])
        self.assertIn("gems/3", snapshot["partitionKind"])

    def test_g2_json_now_exists_and_is_real_valid_gem_content(self) -> None:
        path = GEMS_DIR / "g2.json"
        self.assertTrue(path.exists(), "gems/2 is allocated but g2.json is still missing")
        entries = _load_gem_entries(path)
        self.assertTrue(entries, "g2.json exists but authors zero entries")
        for entry in entries:
            with self.subTest(id=entry.get("id")):
                for required in ("id", "nameKey", "name", "family", "powerBand", "iconKey", "tags"):
                    self.assertIn(required, entry)
                self.assertTrue(entry["id"].startswith("gem.g2-"))
                self.assertTrue(entry["family"].startswith("atom."))
                self.assertIsInstance(entry["tags"], list)
                self.assertTrue(entry["tags"])

    def test_g2_entries_import_cleanly_against_geminsertcorpus_load_shape(self) -> None:
        """Mirrors `GemInsertCorpus.Load` (ItemCardEndpoints.cs) field-by-field: `id` is required,
        everything else defaults rather than throws -- but a REAL gem should never be relying on
        those defaults, so this asserts the authored values are present and non-empty, not merely
        that the loader wouldn't crash."""
        entries = _load_gem_entries(GEMS_DIR / "g2.json")
        for entry in entries:
            with self.subTest(id=entry["id"]):
                self.assertTrue(entry.get("family"))
                self.assertTrue(entry.get("nameKey"))
                self.assertTrue(entry.get("name"))
                # iconKey is derived from nameKey by this module's own emit.icon_key -- prove they
                # actually agree, the same invariant a live loader would silently rely on.
                self.assertEqual(entry["iconKey"], f"icon.{entry['nameKey']}")

    def test_g2_families_resolve_to_the_real_shipped_affix_family_registry(self) -> None:
        """entry-shapes.md §1: `family` "must resolve to a shipped or sibling-authored `atom.*`
        family — `ReferenceUnresolved` else"."""
        entries = _load_gem_entries(GEMS_DIR / "g2.json")
        unresolved = [e["family"] for e in entries if e["family"] not in REAL_FAMILY_IDS]
        self.assertEqual(unresolved, [], f"family ids with no real affix-family entry: {unresolved}")

    def test_g2_does_not_duplicate_any_family_id_or_slot_across_the_partition(self) -> None:
        entries = _load_gem_entries(GEMS_DIR / "g2.json")
        families = [e["family"] for e in entries]
        ids = [e["id"] for e in entries]
        self.assertEqual(len(families), len(set(families)), "a family authored twice in gems/2")
        self.assertEqual(len(ids), len(set(ids)), "an id collision inside gems/2")

    def test_g2_ids_and_names_never_collide_with_the_g1_or_g3_siblings(self) -> None:
        g1 = _load_gem_entries(GEMS_DIR / "g1.json")
        g3 = _load_gem_entries(GEMS_DIR / "g3.json")
        g2 = _load_gem_entries(GEMS_DIR / "g2.json")
        sibling_ids = {e["id"] for e in g1} | {e["id"] for e in g3}
        sibling_names = {e["name"] for e in g1} | {e["name"] for e in g3}
        sibling_families = {e["family"] for e in g1} | {e["family"] for e in g3}
        for entry in g2:
            with self.subTest(id=entry["id"]):
                self.assertNotIn(entry["id"], sibling_ids)
                self.assertNotIn(entry["name"], sibling_names)
                self.assertNotIn(entry["family"], sibling_families)

    def test_g2_seq_range_stays_inside_the_wave_one_range(self) -> None:
        entries = _load_gem_entries(GEMS_DIR / "g2.json")
        for entry in entries:
            seq = int(entry["id"].rsplit("-", 1)[1])
            self.assertTrue(emit.SEQ_MIN <= seq <= emit.SEQ_MAX, entry["id"])


if __name__ == "__main__":
    unittest.main()
