# One-shot generator for mechanism stubs. Not part of CI.
$ErrorActionPreference = "Stop"
$root = $PSScriptRoot

$mechs = @(
  @{ Id="local-control-room"; Name="Local control room"; Status="Shipped"; Loop="Session — how you play"; Pillar="../how-you-play.md"; PillarLabel="How you play"; What="Rise of Summoner runs on your machine. No account, no cloud. The launcher opens the browser control room where Sanctum, lawn, map, and layers live."; How="Start the launcher (or a local deploy). The browser UI is your control room. Your save lives beside the server."; Rel=@("save-select","sanctum") }
  @{ Id="save-select"; Name="Title and save select"; Status="Shipped"; Loop="Session — how you play"; Pillar="../sanctum.md"; PillarLabel="Sanctum"; What="At the door you pick or create a summoner save. That save is the world you keep."; How="On boot, choose an existing save or create one. Updating the RPG keeps that data and does not touch the lawn game's own saves."; Rel=@("local-control-room","sanctum") }
  @{ Id="sanctum"; Name="Sanctum"; Status="Shipped"; Loop="Places — home stage"; Pillar="../sanctum.md"; PillarLabel="Sanctum"; What="Your home hall. Session start and every run return here. Creatures on display, next steps, travel."; How="Land in the Sanctum after save select. Open layers from the rail. Travel to Lawn or World when ready."; Rel=@("layer-rail","naming-ritual") }
  @{ Id="layer-rail"; Name="Layer rail and hotkeys"; Status="Shipped"; Loop="Session — how you play"; Pillar="../sanctum.md"; PillarLabel="Sanctum"; What="Creatures, Commanders, Relics, Fusion, Pacts, Expeditions, Almanac, Chronicle — the same keys everywhere over whatever stage you are on."; How="Use C / K / R / F / P / E / A / H (and Esc for System). Closing a layer returns you to the stage you left."; Rel=@("sanctum","unlock-beats") }
  @{ Id="unlock-beats"; Name="Unlock ladder (play beats)"; Status="Shipped"; Loop="Session — how you play"; Pillar="../how-you-play.md"; PillarLabel="How you play"; What="Layers open as you play. Locked ones say what unlocks them — not invisible, not dead grey weight."; How="Play until the rail opens each layer (first item, first demon to fuse, first bound demon for expeditions, and so on). See How you play for the live table."; Rel=@("layer-rail","unlock-chapters") }
  @{ Id="unlock-chapters"; Name="Dave-level unlock chapters"; Status="Vision"; Loop="Level up and power"; Pillar="../how-you-play.md"; PillarLabel="How you play"; What="Complexity drips by Dave's level so day one is not a spreadsheet. Thresholds live in balance data later."; How="Not in the current loop yet. Today's rail still unlocks on play beats. The Vision table on How you play is the chapter map."; Rel=@("dave-level","unlock-beats") }
  @{ Id="system-settings"; Name="Settings and keymap"; Status="Shipped"; Loop="Session — how you play"; Pillar="../sanctum.md"; PillarLabel="Sanctum"; What="Rebind keys, display options, quit — System on Esc when the layer stack is empty."; How="Press Esc on an empty stack to open System. Change what you need; close to return."; Rel=@("layer-rail","local-control-room") }
  @{ Id="naming-ritual"; Name="First-run naming ritual"; Status="WIP"; Loop="Summon and fusion"; Pillar="../sanctum.md"; PillarLabel="Sanctum"; What="Bind and name your first creature in place at the Sanctum so the roster starts as a story, not a spreadsheet."; How="Not finished yet. When it ships, first session will name a creature before the rail opens fully."; Rel=@("sanctum","specimens") }

  @{ Id="souls"; Name="Souls"; Status="Shipped"; Loop="Summon and fusion · Level up and power"; Pillar="../creatures.md"; PillarLabel="Creatures"; What="Earn from play; spend to summon and bind. One of the three stocks — souls bank across worlds."; How="Play lawn matches and resolve work that pays souls. Spend at the altar and on pacts. Watch the HUD stock."; Rel=@("essence","loam","summoning-altar") }
  @{ Id="essence"; Name="Essence"; Status="Shipped"; Loop="Summon and fusion · Farm / hunt / defend"; Pillar="../creatures.md"; PillarLabel="Creatures"; What="Element-matched materials for fusion and some buildings. Banks with you; not loam."; How="Collect from play and expeditions. Spend into specimen fusion and later sector buildings that ask for an element."; Rel=@("souls","specimen-fusion","sector-buildings") }
  @{ Id="loam"; Name="Loam and the Fracture"; Status="Shipped"; Loop="Farm / hunt / defend · World map"; Pillar="../the-rift.md"; PillarLabel="The rift"; What="Ground pressure on sectors you hold. Neglect fades holdings. Loam never banks across worlds — it is position, not a wallet."; How="Claim and hold sectors. Watch loam on the map. If you neglect ground, the Fracture takes it back."; Rel=@("world-map","farm-hunt-defend","new-world-prestige") }

  @{ Id="specimens"; Name="Persistent specimens"; Status="Shipped"; Loop="Summon and fusion"; Pillar="../creatures.md"; PillarLabel="Creatures"; What="Every demon is an individual — level, gear, history — not a stack of copies. Duplicates have a job in fusion."; How="Open Creatures. Inspect the roster. Deploy bound specimens; send spare ones on expeditions."; Rel=@("summoning-altar","pacts-loyalty","specimen-fusion") }
  @{ Id="summoning-altar"; Name="Summoning altar"; Status="Shipped"; Loop="Summon and fusion"; Pillar="../creatures.md"; PillarLabel="Creatures"; What="Spend souls for new demons. Pity is shown on the altar. Gacha is one path, never the only one."; How="Open Summon / Demons when you have souls. Pull; read pity; add specimens to the roster."; Rel=@("souls","specimens","wild-joins") }
  @{ Id="pacts-loyalty"; Name="Pacts and loyalty"; Status="Shipped"; Loop="Summon and fusion"; Pillar="../creatures.md"; PillarLabel="Creatures"; What="Bind demons to contract slots. Neglect them and they refuse to deploy."; How="Open Pacts. Assign demons to slots. Keep loyalty from decaying under upkeep."; Rel=@("tribute","specimens","lawn-deploy") }
  @{ Id="tribute"; Name="Tribute on pacts"; Status="Shipped"; Loop="Summon and fusion"; Pillar="../creatures.md"; PillarLabel="Creatures"; What="Keep contracts paid. Overdue tribute is leverage against you."; How="Pay tribute when the pact asks. Do not let contracts go overdue if you need that demon in the field."; Rel=@("pacts-loyalty","souls") }
  @{ Id="specimen-fusion"; Name="Specimen fusion"; Status="Shipped"; Loop="Summon and fusion"; Pillar="../creatures.md"; PillarLabel="Creatures"; What="Merge specimens into stronger forms and discover recipes. The Fusion rail key (F) is this lab — not the host game's product name."; How="Open Fusion (F). Pick ingredients, spend essence when asked, learn recipes by trying merges."; Rel=@("essence","specimens","summoning-altar") }
  @{ Id="patron"; Name="Patron demon"; Status="WIP"; Loop="Summon and fusion"; Pillar="../creatures.md"; PillarLabel="Creatures"; What="Name one demon your patron and let its element colour the army."; How="Not finished yet. When it ships, choose a patron from the roster; its element tints side presence."; Rel=@("specimens","element-ring","commanders") }
  @{ Id="capture"; Name="In-run capture"; Status="WIP"; Loop="Farm / hunt / defend · Lawn"; Pillar="../creatures.md"; PillarLabel="Creatures"; What="Weaken a wild demon in play and attempt to catch it — a hunt intake beside altar and wild joins."; How="Not finished yet. Fantasy: pressure a target on the lawn or in a delve, then attempt capture. No legendaries gated this way forever."; Rel=@("wild-joins","lawn-match","delve") }
  @{ Id="wild-joins"; Name="Wild joins"; Status="Shipped"; Loop="Summon and fusion · Idle expeditions"; Pillar="../expeditions.md"; PillarLabel="Expeditions"; What="Demons that join from expedition outcomes — intake that is not the altar."; How="Dispatch expeditions; when a wild join lands, it appears in the roster. Treat it like any specimen afterward."; Rel=@("expeditions","summoning-altar","specimens") }

  @{ Id="dave-level"; Name="Dave's level"; Status="Shipped"; Loop="Level up and power"; Pillar="../relics-and-builds.md"; PillarLabel="Relics and builds"; What="The main power line. Endless — no cap. Later Vision chapters drip complexity by this level."; How="Play. Dave gains level from work done. Spend aptitude points as you earn them. There is no soft ceiling."; Rel=@("aptitudes","type-specimen-xp","unlock-chapters") }
  @{ Id="type-specimen-xp"; Name="Type and specimen XP"; Status="Shipped"; Loop="Level up and power"; Pillar="../almanac.md"; PillarLabel="Almanac"; What="Plants, zombies, and demons grow from work they actually did — type lines and individual specimens."; How="Field units and specimens. Progress shows on Chronicle / roster sheets. Meet types to deepen almanac dossiers."; Rel=@("dave-level","almanac","specimens") }
  @{ Id="aptitudes"; Name="Free-build aptitudes"; Status="Shipped"; Loop="Level up and power"; Pillar="../relics-and-builds.md"; PillarLabel="Relics and builds"; What="Twelve aptitudes. You have no class — points go where you want."; How="Open Builds / progression. Spend aptitude points freely. Respec costs are priced when they apply."; Rel=@("dave-level","species-builds","build-presets") }
  @{ Id="species-builds"; Name="Species builds"; Status="WIP"; Loop="Level up and power"; Pillar="../relics-and-builds.md"; PillarLabel="Relics and builds"; What="Species you field grow their own aptitude lean over time. You can override; changing your mind costs a priced respec."; How="Not finished yet. When it ships, fielding a species steers its lean; override when you need a different face."; Rel=@("aptitudes","specimens") }
  @{ Id="passive-trees"; Name="Passive trees"; Status="Vision"; Loop="Level up and power"; Pillar="../relics-and-builds.md"; PillarLabel="Relics and builds"; What="Spend souls into trees for identity and risk. Many trees can be equal in expected value; concentrating buys reward and risk."; How="Not in the current loop yet. Catalogs will be learnable and shared — not a secret wiki."; Rel=@("dave-level","aptitudes","souls") }
  @{ Id="build-presets"; Name="Build presets"; Status="Vision"; Loop="Item collection · Level up and power"; Pillar="../relics-and-builds.md"; PillarLabel="Relics and builds"; What="Save a synergy loadout — patron, relics, aptitudes, who you field — so a lean is something you keep."; How="Not in the current loop yet. Fantasy: save and swap named presets instead of five independent clicks."; Rel=@("aptitudes","relics-armoury","patron") }
  @{ Id="commanders"; Name="Commanders"; Status="WIP"; Loop="Level up and power · Lawn"; Pillar="../relics-and-builds.md"; PillarLabel="Relics and builds"; What="Choose who leads the next lawn run. The choice persists; a match snapshot freezes the leader when the board starts."; How="Open Commanders (K). Set the leader for the next lawn. You do not mid-wave swap the story."; Rel=@("commander-auras","lawn-match","dave-level") }
  @{ Id="commander-auras"; Name="Commander auras"; Status="WIP"; Loop="Level up and power · Lawn"; Pillar="../relics-and-builds.md"; PillarLabel="Relics and builds"; What="A continuous side-wide presence (or Focus on your own actions) from the leader you chose. One aura active at a time."; How="Not finished yet. When it ships, the commander you set carries one aura into the match."; Rel=@("commanders","lawn-match") }
  @{ Id="relics-armoury"; Name="Relics armoury"; Status="WIP"; Loop="Item collection and progression"; Pillar="../relics-and-builds.md"; PillarLabel="Relics and builds"; What="One vault of gear — find, equip, compare, salvage. Opens as a chapter in the Vision unlock ladder."; How="Not a finished loop yet. Thin surfaces may exist; treat the full armoury fantasy as WIP. No dead loot UI before the chapter opens."; Rel=@("relic-crafting","build-presets","unlock-chapters") }
  @{ Id="relic-crafting"; Name="Relic crafting"; Status="WIP"; Loop="Item collection and progression"; Pillar="../relics-and-builds.md"; PillarLabel="Relics and builds"; What="Sockets, sets, charms, salvage, enhance, named uniques — the deep gear loop."; How="Not finished yet. When it ships, craft and socket in the armoury; enhance and reroll cost something real."; Rel=@("relics-armoury","essence","souls") }

  @{ Id="element-ring"; Name="Six elements and omni"; Status="Shipped"; Loop="Combat (every place)"; Pillar="../combat.md"; PillarLabel="Combat"; What="Fire, ice, air, earth, light, dark — plus omni. Matchups are real numbers, not flavour labels."; How="Field and fight with element in mind. Read matchups on sheets and in combat feedback."; Rel=@("shields-crit-resist","statuses","patron") }
  @{ Id="shields-crit-resist"; Name="Shields, crit, and resistance"; Status="Shipped"; Loop="Combat (every place)"; Pillar="../combat.md"; PillarLabel="Combat"; What="Layered defence and hits that can fail or land hard. Same combat language on the lawn and in later battles."; How="Watch shields and statuses on the unit HUD. Build for crit and resist through gear, aptitudes, and specimen traits."; Rel=@("element-ring","statuses","lawn-mirror-hud") }
  @{ Id="statuses"; Name="Statuses"; Status="Shipped"; Loop="Combat (every place)"; Pillar="../combat.md"; PillarLabel="Combat"; What="Butter, freeze, chill, poison, hypno, wither, contagions, and more — conditions that actually resolve."; How="Apply and cleanse through play. Read icons on the lawn HUD and battle UI when they ship."; Rel=@("element-ring","named-reactions","skills-loadouts") }
  @{ Id="actor-meters"; Name="Actor meters"; Status="WIP"; Loop="Combat (every place)"; Pillar="../combat.md"; PillarLabel="Combat"; What="HP, stamina, sun/hunger, spirit, yang/yin, poise — resources skills and stances spend."; How="Not finished yet. When meters land, skills cost something you can see and guard is a real stance."; Rel=@("skills-loadouts","interactive-battles") }
  @{ Id="skills-loadouts"; Name="Skills and loadouts"; Status="WIP"; Loop="Combat (every place)"; Pillar="../combat.md"; PillarLabel="Combat"; What="Equip a small set of actions — innate, family, signatures — with costs, cooldowns, and targeting."; How="Not finished yet. Loadouts will live on the creature sheet; unlocking a skill is progression, not a second power curve."; Rel=@("actor-meters","interactive-battles","specimens") }
  @{ Id="named-reactions"; Name="Named reactions and combo recipes"; Status="Vision"; Loop="Combat (every place)"; Pillar="../combat.md"; PillarLabel="Combat"; What="A short learnable list on top of the element ring — not a second ring and no new elements."; How="Not in the current loop yet. Interactive battles already name reaction windows; this is the catalog you can study."; Rel=@("element-ring","interactive-battles","statuses") }
  @{ Id="interactive-battles"; Name="Interactive battles"; Status="WIP"; Loop="Combat · Delve · map fights"; Pillar="../combat.md"; PillarLabel="Combat"; What="Turn-based fights you play yourself — initiative, action bar, targets, reactions. Expeditions can stay auto-resolve."; How="Not finished yet. Today many web fights auto-resolve with the same math. When the battle stage ships, you pilot turns."; Rel=@("skills-loadouts","named-reactions","map-battle-handoff") }

  @{ Id="lawn-match"; Name="Lawn match"; Status="Shipped"; Loop="Lawn — first core"; Pillar="../the-lawn.md"; PillarLabel="The lawn"; What="A live board match (Plants vs. Zombies: Fusion on your machine). First core loop — feeds souls, XP, almanac, deploy. Not the whole war."; How="Start a legal lawn-game match. Open the Lawn stage in the control room. Play; progress lands in your Rise of Summoner save."; Rel=@("lawn-mirror-hud","lawn-deploy","souls") }
  @{ Id="lawn-mirror-hud"; Name="Live mirror and unit HUD"; Status="Shipped"; Loop="Lawn — first core"; Pillar="../the-lawn.md"; PillarLabel="The lawn"; What="Watch the 12x5 board in the browser. Unit HUD shows identity, shield, and statuses above each unit."; How="With a match running, open Lawn. Read the mirror and HUD under pressure without opening a second physics engine."; Rel=@("lawn-match","statuses","shields-crit-resist") }
  @{ Id="lawn-deploy"; Name="Bound demon deploy"; Status="Shipped"; Loop="Lawn — first core · Summon and fusion"; Pillar="../the-lawn.md"; PillarLabel="The lawn"; What="Deploy roster demons into a lawn run as plant-side avatars (or designated hypno-zombie allies)."; How="Bind demons on pacts. During a match, deploy those who are not locked on an expedition."; Rel=@("pacts-loyalty","specimens","lawn-match") }
  @{ Id="lawn-blessing"; Name="Lawn blessing"; Status="WIP"; Loop="Lawn — first core · Idle expeditions"; Pillar="../the-lawn.md"; PillarLabel="The lawn"; What="A real lawn run charges stronger soul earn on the next stretch of web expeditions — lawn makes idle better."; How="Not finished yet. Fantasy: finish a strong match, then collect better from the next idle waves."; Rel=@("lawn-match","expeditions","souls") }
  @{ Id="lawn-trophies"; Name="Lawn trophies"; Status="WIP"; Loop="Lawn — first core"; Pillar="../the-lawn.md"; PillarLabel="The lawn"; What="Cosmetic prestige from lawn play — never stats, never a repeatable faucet."; How="Not finished yet. When it ships, earn trophies from play for display only."; Rel=@("lawn-match","chronicle") }
  @{ Id="in-game-open"; Name="In-game open control room"; Status="WIP"; Loop="Lawn — first core"; Pillar="../the-lawn.md"; PillarLabel="The lawn"; What="Open the RPG without leaving the lawn-game window (button / F10). Esc closes; the board pauses while you are away."; How="Not finished yet. Today the usual path is launcher + browser."; Rel=@("local-control-room","lawn-match") }

  @{ Id="expeditions"; Name="Expeditions"; Status="Shipped"; Loop="Idle expeditions — core forever"; Pillar="../expeditions.md"; PillarLabel="Expeditions"; What="Dispatch spare demons, wait (30 min to 20 h), collect. No stamina. Sibling of the Delve, not a throwaway."; How="Open Expeditions. Pick demons not on a live task. Dispatch a duration tier. Collect when ready."; Rel=@("expedition-slots-recall","wild-joins","essence") }
  @{ Id="expedition-slots-recall"; Name="Expedition slots and recall"; Status="Shipped"; Loop="Idle expeditions"; Pillar="../expeditions.md"; PillarLabel="Expeditions"; What="Grow parallel slots. Recall early for pro-rated rewards."; How="Unlock more slots as the system allows. Recall if you need the demons back before the timer ends."; Rel=@("expeditions","specimens") }
  @{ Id="expedition-event-ticks"; Name="Expedition quest and event ticks"; Status="Vision"; Loop="Quests and events · Idle expeditions"; Pillar="../expeditions.md"; PillarLabel="Expeditions"; What="Idle ticks that open quests and world events — story clock, not only loot."; How="Not in the current loop yet beyond thin expedition event ticks. Full quest handoff is Vision."; Rel=@("expeditions","quest-log","world-events") }

  @{ Id="world-map"; Name="Rift world map"; Status="Shipped"; Loop="World-map adventure"; Pillar="../the-rift.md"; PillarLabel="The rift"; What="Sectors, lanes, legions — where you go. Fog, march, claim, Zomboss in his own fog."; How="Travel to World. Move legions along lanes. Claim sectors. Press End Turn when orders are set."; Rel=@("virtual-turns","fog-of-war","loam") }
  @{ Id="virtual-turns"; Name="World virtual turns"; Status="Shipped"; Loop="World map · World stage"; Pillar="../the-rift.md"; PillarLabel="The rift"; What="End Turn commits everyone's orders. The world clock is virtual turns — not a real-life diary."; How="Set orders for your legions. Press End Turn. Everyone resolves, including Zomboss."; Rel=@("world-map","zomboss-commander") }
  @{ Id="fog-of-war"; Name="Fog of war"; Status="Shipped"; Loop="World-map adventure"; Pillar="../the-rift.md"; PillarLabel="The rift"; What="Your ground is clear; other people's ground and the past stay uncertain. Zomboss evaluates from his fog."; How="Hold sectors for clear sight. Scout carefully into uncertain ground."; Rel=@("world-map","zomboss-commander") }
  @{ Id="zomboss-commander"; Name="Zomboss as commander"; Status="Shipped"; Loop="World-map adventure · Farm / hunt / defend"; Pillar="../the-rift.md"; PillarLabel="The rift"; What="He runs his own war from his own fog. Find his fortress before your homeworld falls."; How="Advance the map. Read his moves after End Turn. Win and lose are defined on The game."; Rel=@("world-map","virtual-turns","farm-hunt-defend") }
  @{ Id="farm-hunt-defend"; Name="Farm, hunt, and defend"; Status="Shipped (thin)"; Loop="Farm / hunt / defend"; Pillar="../the-rift.md"; PillarLabel="The rift"; What="Territorial loop — yield and materials; prey and capture; Seat and homeworld. Full ecology and sieges deepen later."; How="Hold ground for farm. Hunt through lawn, capture, delves, map prey. Defend loam and the homeworld."; Rel=@("loam","capture","siege") }
  @{ Id="sector-buildings"; Name="Sector buildings"; Status="WIP"; Loop="World-stage empire · Farm"; Pillar="../the-rift.md"; PillarLabel="The rift"; What="Wells, waystations, granaries — economy on ground you hold. Costs in loam and sometimes essence."; How="Not finished yet. When it ships, raise buildings inside held sectors from the empire surface."; Rel=@("loam","essence","world-stage") }
  @{ Id="map-orders"; Name="Map tools and orders"; Status="WIP"; Loop="World-map adventure"; Pillar="../the-rift.md"; PillarLabel="The rift"; What="Wardens, cede, dowse, lenses, outliner — tools beyond basic march and claim."; How="Not finished yet. Fantasy: bind wardens, give up sectors on purpose, switch map lenses."; Rel=@("world-map","farm-hunt-defend") }
  @{ Id="map-battle-handoff"; Name="Map to battle handoff"; Status="WIP"; Loop="World-map adventure · Combat"; Pillar="../the-rift.md"; PillarLabel="The rift"; What="Commit a legion into a fight. The map hands a battle a request and consumes an outcome."; How="Not finished yet. Needs interactive battles you play yourself for the full fantasy."; Rel=@("world-map","interactive-battles") }
  @{ Id="world-stage"; Name="World-stage empire"; Status="Vision"; Loop="World-stage empire building"; Pillar="../the-rift.md"; PillarLabel="The rift"; What="Where you stand to run the empire — camera, HUD, inspector, End Turn — not a flowchart with a sidebar of buttons."; How="Not in the current loop as a finished place. Thin map surface is playable today; full stage is Vision."; Rel=@("world-map","sector-buildings","virtual-turns") }
  @{ Id="three-layer-world"; Name="Three-layer world"; Status="Vision"; Loop="World map · World stage"; Pillar="../the-rift.md"; PillarLabel="The rift"; What="Rift graph, sector board, lane board — three layers of the war presentation."; How="Not in the current loop yet. Graph is what you play today."; Rel=@("world-map","world-stage","map-battle-handoff") }
  @{ Id="world-generator"; Name="World generator and deeper fog"; Status="Vision"; Loop="World-map adventure"; Pillar="../the-rift.md"; PillarLabel="The rift"; What="Procedural maps and richer scouting craft."; How="Not in the current loop yet."; Rel=@("fog-of-war","world-map") }
  @{ Id="counter-development"; Name="Enemy counter-development"; Status="Vision"; Loop="Farm / hunt / defend · World events"; Pillar="../the-rift.md"; PillarLabel="The rift"; What="The war shifts resists and composition from how you play — not matched levels. Raise demons, a strategy works, the world counters, rebuild."; How="Not in the current loop yet."; Rel=@("zomboss-commander","farm-hunt-defend","world-events") }

  @{ Id="delve"; Name="The Delve"; Status="Vision"; Loop="Dungeon crawler — the Delve"; Pillar="../delves-and-sieges.md"; PillarLabel="Delves and sieges"; What="Party crawl through seeded rooms toward a boss — haul out or fail trying."; How="Not in the current loop yet. Domains are found in the world, then entered from the Sanctum."; Rel=@("pack-extract-oaths","party-formations","interactive-battles") }
  @{ Id="pack-extract-oaths"; Name="Pack, extract, oaths, domains"; Status="Vision"; Loop="Dungeon crawler — the Delve"; Pillar="../delves-and-sieges.md"; PillarLabel="Delves and sieges"; What="Provision a pack, enter a found domain, extract with a haul or wipe. Optional hard oaths on difficulty rungs."; How="Not in the current loop yet."; Rel=@("delve","failure-branches","party-formations") }
  @{ Id="party-formations"; Name="Party formations and combo skills"; Status="Vision"; Loop="Delve · Interactive battles"; Pillar="../delves-and-sieges.md"; PillarLabel="Delves and sieges"; What="How the pack stands, and a few combination skills — a second axis besides who is in the party. Expeditions stay auto-resolve."; How="Not in the current loop yet."; Rel=@("delve","interactive-battles","pack-extract-oaths") }
  @{ Id="siege"; Name="Siege"; Status="Vision"; Loop="Farm / hunt / defend"; Pillar="../delves-and-sieges.md"; PillarLabel="Delves and sieges"; What="Defend or assault the Seat on a tactical board — buildings as actors, occupy to possess."; How="Not in the current loop yet."; Rel=@("farm-hunt-defend","world-map","interactive-battles") }

  @{ Id="quest-log"; Name="Quest log"; Status="Vision"; Loop="Quests and events"; Pillar="../how-you-play.md"; PillarLabel="How you play"; What="Track quests and events as a layer you can open — story clock, not only loot."; How="Not in the current loop yet. Named so it cannot stay invisible."; Rel=@("world-events","expedition-event-ticks","failure-branches") }
  @{ Id="world-events"; Name="World events and raids"; Status="Vision"; Loop="Quests and events · World"; Pillar="../the-rift.md"; PillarLabel="The rift"; What="Blood moons, roaming bosses, ecology — the world pushes back on a schedule of events."; How="Not in the current loop yet."; Rel=@("quest-log","counter-development","farm-hunt-defend") }
  @{ Id="failure-branches"; Name="Failure branches"; Status="Vision"; Loop="Quests · Farm / hunt / defend · Delve"; Pillar="../delves-and-sieges.md"; PillarLabel="Delves and sieges"; What="A lost sector, failed extract, or failed defense can open different ground — not only a wipe. Consequence as content."; How="Not in the current loop yet."; Rel=@("quest-log","delve","farm-hunt-defend") }
  @{ Id="almanac"; Name="Almanac dossiers"; Status="Shipped"; Loop="Level up and power · Lawn"; Pillar="../almanac.md"; PillarLabel="Almanac"; What="Meet it in play and it files itself — dossiers from your own playthrough, not a wiki someone else wrote."; How="Open Almanac after you have met things in play. Browse dossiers and fusion recipes you uncovered."; Rel=@("chronicle","type-specimen-xp","lawn-match") }
  @{ Id="chronicle"; Name="Chronicle"; Status="Shipped"; Loop="Level up and power"; Pillar="../almanac.md"; PillarLabel="Almanac"; What="Run history, progression, lasting record of what you did."; How="Open Chronicle (H). Read history and progression. It is the ledger of your summoner story."; Rel=@("almanac","dave-level","new-world-prestige") }
  @{ Id="new-world-prestige"; Name="New world — keep who you are"; Status="Shipped (fiction)"; Loop="Level up and power · Farm / hunt / defend"; Pillar="../the-game.md"; PillarLabel="The game"; What="You keep who you are; you lose where you were. Roster, souls, and essence bank; loam and failed-map holdings do not. Ending a world is progression, not a prestige wipe of the summoner."; How="Win or lose a world per The game. Start another with your roster and stocks that bank. Loam resets with the map."; Rel=@("loam","souls","dave-level") }
)

function RelLinks($ids) {
  ($ids | ForEach-Object { "- [$($_)]($_ .md)" -replace ' .md','.md' }) -join "`n"
}

foreach ($m in $mechs) {
  $rel = ($m.Rel | ForEach-Object { "- [$($_)]($_.md)" }) -join "`n"
  $body = @"
# $($m.Name)

**Status:** $($m.Status)
**Loop:** $($m.Loop) — see [The loops](../the-loops.md)
**Pillar:** [$($m.PillarLabel)]($($m.Pillar))

## What it is

$($m.What)

## How you use it

$($m.How)

## Related

$rel
- Pillar: [$($m.PillarLabel)]($($m.Pillar))
- [Mechanism index](README.md)
"@
  Set-Content -Path (Join-Path $root "$($m.Id).md") -Value $body.TrimEnd() -Encoding utf8
}

Write-Output ("Wrote {0} stubs" -f $mechs.Count)
