// <auto-generated>
// Generated by tools/ElementEnumGen --effect-emit from data/seed/atoms/fx-*.json.
// Compiled via AtomCompiler.Compile(..., RuntimeId.Lawn, ...) then AtomPushCodec.ToDef —
// proven identical to the retired hand-written EffectSeedCatalog by
// MigrationParityTests (DTO shape) and EffectCatalogExecutionParityTests (real scenario runs).
// Do not hand-edit — edit data/seed/atoms/fx-*.json and regenerate.
// </auto-generated>
namespace FusionRpg.Core.Effects;

public static class EffectAtomCatalog
{
    public static IReadOnlyList<EffectDef> CreateAll() => new List<EffectDef>
    {
        new()
        {
            EffectId = "fx.board_cherry",
            EffectType = "Triggered",
            Name = "Board cherry bomb",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() { "OnDamageDealt" },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "BoardAction",
                    Params = new()
                    {
                        ["col"] = 4.0,
                        ["op"] = "cherry",
                        ["row"] = 2.0,
                    },
                },
            },
        },
        new()
        {
            EffectId = "fx.butter_on_hit",
            EffectType = "Triggered",
            Name = "Butter on hit",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() { "OnDamageDealt" },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "ApplyStatus",
                    Params = new()
                    {
                        ["duration"] = 4,
                        ["status"] = "butter",
                    },
                },
            },
        },
        new()
        {
            EffectId = "fx.clear_butter",
            EffectType = "Triggered",
            Name = "Clear butter",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() { "OnDamageDealt" },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "ClearStatus",
                    Params = new()
                    {
                        ["status"] = "butter",
                    },
                },
            },
        },
        new()
        {
            EffectId = "fx.cold_on_hit",
            EffectType = "Triggered",
            Name = "Cold on hit",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() { "OnDamageDealt" },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "ApplyStatus",
                    Params = new()
                    {
                        ["duration"] = 5,
                        ["status"] = "cold",
                    },
                },
            },
        },
        new()
        {
            EffectId = "fx.economy_sun",
            EffectType = "Triggered",
            Name = "Add sun",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() { "OnDamageDealt" },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "Economy",
                    Params = new()
                    {
                        ["amount"] = 25,
                        ["currency"] = "sun",
                        ["op"] = "add",
                    },
                },
            },
        },
        new()
        {
            EffectId = "fx.freeze_on_hit",
            EffectType = "Triggered",
            Name = "Freeze on hit",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() { "OnDamageDealt" },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "ApplyStatus",
                    Params = new()
                    {
                        ["duration"] = 3,
                        ["status"] = "freeze",
                    },
                },
            },
        },
        new()
        {
            EffectId = "fx.grid_item_cycle",
            EffectType = "Triggered",
            Name = "Spawn + clear grid item",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() { "OnDamageDealt" },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "SpawnGridItem",
                    Params = new()
                    {
                        ["col"] = 3.0,
                        ["gridItemType"] = 7.0,
                        ["row"] = 2.0,
                    },
                },
                new()
                {
                    Seq = 2,
                    Action = "ClearGridItem",
                    Params = new()
                    {
                        ["col"] = 3.0,
                        ["gridItemType"] = 7.0,
                        ["row"] = 2.0,
                    },
                },
            },
        },
        new()
        {
            EffectId = "fx.icd_butter",
            EffectType = "Triggered",
            Name = "ICD butter",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() { "OnDamageDealt" },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "ApplyStatus",
                    Params = new()
                    {
                        ["duration"] = 2,
                        ["status"] = "butter",
                    },
                },
            },
        },
        new()
        {
            EffectId = "fx.overlay_damage",
            EffectType = "Triggered",
            Name = "Overlay HP delta",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() { "OnDamageDealt" },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "ApplyResourceDelta",
                    Params = new()
                    {
                        ["channel"] = "hp",
                    },
                },
            },
        },
        new()
        {
            EffectId = "fx.passive_atk_flat",
            EffectType = "Passive",
            Name = "Passive ATK +10",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() {  },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "ModifyStat",
                    Params = new()
                    {
                        ["flat"] = 10,
                        ["channel"] = "atk",
                    },
                },
            },
        },
        new()
        {
            EffectId = "fx.poison_on_hit",
            EffectType = "Triggered",
            Name = "Poison on hit",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() { "OnDamageDealt" },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "ApplyStatus",
                    Params = new()
                    {
                        ["duration"] = 5,
                        ["status"] = "poison",
                    },
                },
            },
        },
        new()
        {
            EffectId = "fx.set_dirt_box",
            EffectType = "Triggered",
            Name = "Set dirt box",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() { "OnDamageDealt" },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "SetBoxType",
                    Params = new()
                    {
                        ["boxType"] = 2.0,
                        ["col"] = 3.0,
                        ["row"] = 2.0,
                    },
                },
            },
        },
        new()
        {
            EffectId = "fx.shield_grant",
            EffectType = "Triggered",
            Name = "Grant shield",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() { "OnDamageDealt", "OnSpawn", "OnTimer" },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "GrantShield",
                    Params = new()
                    {
                    },
                },
            },
        },
        new()
        {
            EffectId = "fx.spawn_butter",
            EffectType = "Triggered",
            Name = "Butter on spawn",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() { "OnSpawn" },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "ApplyStatus",
                    Params = new()
                    {
                        ["duration"] = 3,
                        ["status"] = "butter",
                    },
                },
            },
        },
        new()
        {
            EffectId = "fx.spawn_plant_bullet",
            EffectType = "Triggered",
            Name = "Spawn plant + bullet",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() { "OnDamageDealt" },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "SpawnEntity",
                    Params = new()
                    {
                        ["col"] = 3.0,
                        ["kind"] = "plant",
                        ["row"] = 2.0,
                        ["typeId"] = 0.0,
                    },
                },
                new()
                {
                    Seq = 2,
                    Action = "SpawnEntity",
                    Params = new()
                    {
                        ["kind"] = "bullet",
                        ["row"] = 2.0,
                        ["typeId"] = 0.0,
                        ["x"] = 400,
                    },
                },
            },
        },
        new()
        {
            EffectId = "fx.spawn_zombie_ondeath",
            EffectType = "Triggered",
            Name = "Spawn zombie on death",
            Enabled = true,
            SourceTag = "atom",
            Triggers = new() { "OnDeath" },
            Actions = new()
            {
                new()
                {
                    Seq = 1,
                    Action = "SpawnEntity",
                    Params = new()
                    {
                        ["hp"] = 100,
                        ["kind"] = "zombie",
                        ["maxHp"] = 100,
                        ["typeId"] = 0.0,
                    },
                },
            },
        },
    };
}
