using System.Globalization;
using System.Text;
using FusionRpg.Core.Effects;

namespace FusionRpg.Tools.ElementEnumGen;

/// <summary>
/// Emits the generated replacement for <c>EffectSeedCatalog.CreateAll()</c> (E23/E11 Step 4,
/// completeness-audit.md B2) — literal C# object construction, the same style
/// <c>CreatureSpeciesCatalog.Generated.cs</c> already uses, never embedded JSON parsed at runtime.
/// Core must not hold a runtime content loader; a checked-in generated file is not one.
/// </summary>
public static class EffectCatalogGen
{
    /// <summary>
    /// Compiles the named fx-*.json seed files (an explicit allow-list, E43 spec-family-expand.md §3.3 —
    /// never a glob) and renders the catalog source. Code 0 = Source set; 1 = compile refused; 2 = parse
    /// failure. Message carries the def count on success, the reason otherwise.
    /// </summary>
    public static (int Code, string? Source, string Message) GenerateFromSeed(string seedRoot, IReadOnlyList<string> shippedFxFiles)
    {
        var atomsDir = Path.Combine(seedRoot, "atoms");
        var files = shippedFxFiles
            .Select(name => Path.Combine(atomsDir, name))
            .Where(File.Exists)
            .OrderBy(f => f, StringComparer.Ordinal)
            .Select(f => (f, File.ReadAllText(f)))
            .ToArray();

        var collected = FusionRpg.Core.Effects.Atoms.AtomSeedFile.Collect(files);
        if (!collected.IsOk)
            return (2, null, "data/seed/atoms/fx-*.json did not parse:" + Environment.NewLine + "  " +
                string.Join(Environment.NewLine + "  ", collected.Errors));

        var compiled = FusionRpg.Core.Effects.Atoms.AtomCompiler.Compile(
            collected.Content.Atoms, FusionRpg.Core.Effects.Atoms.RuntimeId.Lawn, 1, hostIsPlanner: true);
        if (compiled.Rejected.Count > 0 || compiled.Runtime.Count > 0)
            return (1, null,
                $"refusing to emit: {compiled.Rejected.Count} rejected atom(s), {compiled.Runtime.Count} " +
                "routed to the runner — the retired EffectSeedCatalog's replacement must compile whole");

        var defs = compiled.Defs.Select(FusionRpg.Core.Effects.Atoms.AtomPushCodec.ToDef).ToList();
        return (0, GenerateSource(defs), $"{defs.Count} def(s)");
    }

    /// <summary>Generated vs checked-in text, line-ending insensitive (git may normalise CRLF/LF).</summary>
    public static bool Matches(string generated, string checkedIn) =>
        string.Equals(Normalize(generated), Normalize(checkedIn), StringComparison.Ordinal);

    static string Normalize(string s) => s.Replace("\r\n", "\n");

    public static string GenerateSource(IReadOnlyList<EffectDef> defs)
    {
        var w = new StringBuilder();
        w.AppendLine("// <auto-generated>");
        w.AppendLine("// Generated by tools/ElementEnumGen --effect-emit from data/seed/atoms/fx-*.json.");
        w.AppendLine("// Compiled via AtomCompiler.Compile(..., RuntimeId.Lawn, ...) then AtomPushCodec.ToDef —");
        w.AppendLine("// proven identical to the retired hand-written EffectSeedCatalog by");
        w.AppendLine("// MigrationParityTests (DTO shape) and EffectCatalogExecutionParityTests (real scenario runs).");
        w.AppendLine("// Do not hand-edit — edit data/seed/atoms/fx-*.json and regenerate.");
        w.AppendLine("// </auto-generated>");
        w.AppendLine("namespace FusionRpg.Core.Effects;");
        w.AppendLine();
        w.AppendLine("public static class EffectAtomCatalog");
        w.AppendLine("{");
        w.AppendLine("    public static IReadOnlyList<EffectDef> CreateAll() => new List<EffectDef>");
        w.AppendLine("    {");
        foreach (var def in defs) EmitDef(w, def);
        w.AppendLine("    };");
        w.AppendLine("}");
        return w.ToString();
    }

    static void EmitDef(StringBuilder w, EffectDef def)
    {
        w.AppendLine("        new()");
        w.AppendLine("        {");
        w.AppendLine($"            EffectId = {Str(def.EffectId)},");
        w.AppendLine($"            EffectType = {Str(def.EffectType)},");
        w.AppendLine($"            Name = {Str(def.Name)},");
        w.AppendLine($"            Enabled = {(def.Enabled ? "true" : "false")},");
        w.AppendLine($"            SourceTag = {Str(def.SourceTag)},");
        w.AppendLine($"            Triggers = new() {{ {string.Join(", ", def.Triggers.Select(Str))} }},");
        w.AppendLine("            Actions = new()");
        w.AppendLine("            {");
        foreach (var action in def.Actions)
        {
            w.AppendLine("                new()");
            w.AppendLine("                {");
            w.AppendLine($"                    Seq = {action.Seq},");
            w.AppendLine($"                    Action = {Str(action.Action)},");
            w.AppendLine("                    Params = new()");
            w.AppendLine("                    {");
            foreach (var (key, value) in action.Params)
                w.AppendLine($"                        [{Str(key)}] = {Literal(value)},");
            w.AppendLine("                    },");
            w.AppendLine("                },");
        }
        w.AppendLine("            },");
        w.AppendLine("        },");
    }

    static string Str(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    static string Literal(object? value) => value switch
    {
        null => "null",
        string s => Str(s),
        bool b => b ? "true" : "false",
        int i => i.ToString(CultureInfo.InvariantCulture),
        long l => l.ToString(CultureInfo.InvariantCulture) + "L",
        double d => d.ToString("R", CultureInfo.InvariantCulture).Contains('.') || d.ToString("R", CultureInfo.InvariantCulture).Contains('E')
            ? d.ToString("R", CultureInfo.InvariantCulture)
            : d.ToString("R", CultureInfo.InvariantCulture) + ".0",
        // An event-linked ValueSpec (spec-value-spec-and-curve.md "Event-linked magnitudes") compiles
        // to a nested {"eventField":..., "multiplierMilli":...} marker — the first shipped atom to use
        // it (fx.overlay_damage). A dictionary is otherwise an object-graph shape this catalog never
        // carries, so this stays narrow (dictionary-of-primitives only) rather than a general
        // recursive-literal escape hatch.
        System.Collections.Generic.Dictionary<string, object?> nested =>
            "new Dictionary<string, object?> { " +
            string.Join(", ", nested.Select(kv => $"[{Str(kv.Key)}] = {Literal(kv.Value)}")) +
            " }",
        _ => throw new NotSupportedException(
            $"EffectCatalogGen has no literal emission for value type {value.GetType().FullName} ('{value}') — " +
            "the real 16 defs carry only string/int/double; a new type means new content this generator " +
            "must be taught, not silently mis-emitted."),
    };
}
