using System.Globalization;
using System.Text;
using FusionRpg.Core.Effects;

namespace FusionRpg.Tools.ElementEnumGen;

/// <summary>
/// Emits the generated replacement for <c>EffectSeedCatalog.CreateAll()</c> (E23/E11 Step 4,
/// completeness-audit.md B2) — literal C# object construction, the same style
/// <c>DemonSpeciesCatalog.Generated.cs</c> already uses, never embedded JSON parsed at runtime.
/// Core must not hold a runtime content loader; a checked-in generated file is not one.
/// </summary>
public static class EffectCatalogGen
{
    public static string GenerateSource(IReadOnlyList<EffectDef> defs)
    {
        var w = new StringBuilder();
        w.AppendLine("// <auto-generated>");
        w.AppendLine("// Generated by tools/ElementEnumGen --effect-emit from data/seed/atoms/fx-*.json.");
        w.AppendLine("// Compiled via AtomCompiler.Compile(..., RuntimeId.Lawn, ...) then AtomPushCodec.ToDef —");
        w.AppendLine("// proven identical to the retired hand-written EffectSeedCatalog by");
        w.AppendLine("// MigrationParityTests (DTO shape) and EffectCatalogExecutionParityTests (real scenario runs).");
        w.AppendLine("// Do not hand-edit — edit data/seed/atoms/fx-*.json and regenerate.");
        w.AppendLine("// </auto-generated>");
        w.AppendLine("namespace FusionRpg.Core.Effects;");
        w.AppendLine();
        w.AppendLine("public static class EffectAtomCatalog");
        w.AppendLine("{");
        w.AppendLine("    public static IReadOnlyList<EffectDef> CreateAll() => new List<EffectDef>");
        w.AppendLine("    {");
        foreach (var def in defs) EmitDef(w, def);
        w.AppendLine("    };");
        w.AppendLine("}");
        return w.ToString();
    }

    static void EmitDef(StringBuilder w, EffectDef def)
    {
        w.AppendLine("        new()");
        w.AppendLine("        {");
        w.AppendLine($"            EffectId = {Str(def.EffectId)},");
        w.AppendLine($"            EffectType = {Str(def.EffectType)},");
        w.AppendLine($"            Name = {Str(def.Name)},");
        w.AppendLine($"            Enabled = {(def.Enabled ? "true" : "false")},");
        w.AppendLine($"            SourceTag = {Str(def.SourceTag)},");
        w.AppendLine($"            Triggers = new() {{ {string.Join(", ", def.Triggers.Select(Str))} }},");
        w.AppendLine("            Actions = new()");
        w.AppendLine("            {");
        foreach (var action in def.Actions)
        {
            w.AppendLine("                new()");
            w.AppendLine("                {");
            w.AppendLine($"                    Seq = {action.Seq},");
            w.AppendLine($"                    Action = {Str(action.Action)},");
            w.AppendLine("                    Params = new()");
            w.AppendLine("                    {");
            foreach (var (key, value) in action.Params)
                w.AppendLine($"                        [{Str(key)}] = {Literal(value)},");
            w.AppendLine("                    },");
            w.AppendLine("                },");
        }
        w.AppendLine("            },");
        w.AppendLine("        },");
    }

    static string Str(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    static string Literal(object? value) => value switch
    {
        null => "null",
        string s => Str(s),
        bool b => b ? "true" : "false",
        int i => i.ToString(CultureInfo.InvariantCulture),
        long l => l.ToString(CultureInfo.InvariantCulture) + "L",
        double d => d.ToString("R", CultureInfo.InvariantCulture).Contains('.') || d.ToString("R", CultureInfo.InvariantCulture).Contains('E')
            ? d.ToString("R", CultureInfo.InvariantCulture)
            : d.ToString("R", CultureInfo.InvariantCulture) + ".0",
        _ => throw new NotSupportedException(
            $"EffectCatalogGen has no literal emission for value type {value.GetType().FullName} ('{value}') — " +
            "the real 16 defs carry only string/int/double; a new type means new content this generator " +
            "must be taught, not silently mis-emitted."),
    };
}
