using FusionRpg.Core.Combat.Element;
using FusionRpg.Core.Stats.Derived;

namespace FusionRpg.Tools.ElementEnumGen;

/// <summary>
/// Whether the hand-written <c>ElementTypeId</c> enum and its three companion switches
/// (<c>ElementRoster.Concrete</c>/<c>TryParse</c>, <c>ElementTypeIdExtensions.ToElementId</c>,
/// <c>ElementTable.IdOf</c>) still agree with the authored roster (E23, completeness-audit.md B2).
///
/// <para>All four are already guarded individually by <c>ElementRosterDataTests</c>
/// (<c>The_enum_and_the_roster_agree_on_order</c>) and are not, today, drifted — this class exists so
/// a build-time tool can say so mechanically instead of a person re-deriving it, and so a future
/// roster change has one command to check against rather than four hand-kept switches to remember.</para>
/// </summary>
public sealed record MismatchReport(IReadOnlyList<string> Mismatches)
{
    public bool IsOk => Mismatches.Count == 0;
}

public static class ElementEnumCheck
{
    /// <summary>Every disagreement found, empty when the hand-written code and the roster agree.</summary>
    public static MismatchReport Run(IReadOnlyList<ElementRow> roster)
    {
        var mismatches = new List<string>();
        var ordered = roster.OrderBy(r => r.Ordinal).ToList();

        var enumNames = Enum.GetNames<ElementTypeId>();
        if (enumNames.Length != ordered.Count)
            mismatches.Add($"ElementTypeId has {enumNames.Length} member(s), the roster has {ordered.Count}");

        for (var i = 0; i < ordered.Count && i < enumNames.Length; i++)
        {
            var expected = Pascal(ordered[i].ElementId);
            if (!string.Equals(enumNames[i], expected, StringComparison.Ordinal))
                mismatches.Add(
                    $"ElementTypeId member {i} is '{enumNames[i]}', roster ordinal {ordered[i].Ordinal} " +
                    $"is '{ordered[i].ElementId}' (expected enum member '{expected}')");
        }

        var concreteIds = ElementRoster.Concrete.Select(ElementTable.IdOf).ToList();
        var rosterIds = ordered.Select(r => r.ElementId).ToList();
        if (!concreteIds.SequenceEqual(rosterIds, StringComparer.Ordinal))
            mismatches.Add(
                $"ElementRoster.Concrete order [{string.Join(",", concreteIds)}] != " +
                $"roster order [{string.Join(",", rosterIds)}]");

        foreach (var row in ordered)
        {
            if (!ElementRoster.TryParse(row.ElementId, out var parsed))
            {
                mismatches.Add($"ElementRoster.TryParse does not recognise '{row.ElementId}'");
                continue;
            }

            if (!string.Equals(ElementTable.IdOf(parsed), row.ElementId, StringComparison.Ordinal))
                mismatches.Add(
                    $"ElementTable.IdOf(ElementRoster.TryParse('{row.ElementId}')) = " +
                    $"'{ElementTable.IdOf(parsed)}', round-trip broken");
        }

        foreach (var id in Enum.GetValues<ElementTypeId>())
        {
            var viaExtension = id.ToElementId();
            var viaTable = ElementTable.IdOf(id);
            if (!string.Equals(viaExtension, viaTable, StringComparison.Ordinal))
                mismatches.Add($"{id}: ToElementId() = '{viaExtension}' but ElementTable.IdOf = '{viaTable}'");
        }

        return new MismatchReport(mismatches);
    }

    /// <summary>
    /// The generated source <c>ActorElementTypes.cs</c> would carry if the four hand-kept members
    /// were derived from the roster rather than typed — offered for review, never written over the
    /// hand-written file automatically. See E23's todo entry for why integration stays a deliberate,
    /// separately-reviewed step.
    /// </summary>
    public static string GenerateSource(IReadOnlyList<ElementRow> roster)
    {
        var ordered = roster.OrderBy(r => r.Ordinal).ToList();
        var w = new System.Text.StringBuilder();

        w.AppendLine("// <auto-generated>");
        w.AppendLine("// Generated by tools/ElementEnumGen from data/seed/elements/roster.json.");
        w.AppendLine("// Do not hand-edit — edit the roster and regenerate.");
        w.AppendLine("// </auto-generated>");
        w.AppendLine("namespace FusionRpg.Core.Stats.Derived;");
        w.AppendLine();
        w.AppendLine("public enum ElementTypeId");
        w.AppendLine("{");
        for (var i = 0; i < ordered.Count; i++)
            w.AppendLine($"    {Pascal(ordered[i].ElementId)}{(i < ordered.Count - 1 ? "," : "")}");
        w.AppendLine("}");
        w.AppendLine();
        w.AppendLine("public static partial class ElementRoster");
        w.AppendLine("{");
        w.AppendLine("    public static readonly IReadOnlyList<ElementTypeId> Concrete = new[]");
        w.AppendLine("    {");
        foreach (var row in ordered)
            w.AppendLine($"        ElementTypeId.{Pascal(row.ElementId)},");
        w.AppendLine("    };");
        w.AppendLine();
        w.AppendLine("    public static bool TryParse(string? value, out ElementTypeId id)");
        w.AppendLine("    {");
        w.AppendLine("        switch ((value ?? \"\").Trim().ToLowerInvariant())");
        w.AppendLine("        {");
        foreach (var row in ordered)
            w.AppendLine($"            case \"{row.ElementId}\": id = ElementTypeId.{Pascal(row.ElementId)}; return true;");
        w.AppendLine("            default: id = default; return false;");
        w.AppendLine("        }");
        w.AppendLine("    }");
        w.AppendLine("}");
        w.AppendLine();
        w.AppendLine("public static class ElementTypeIdExtensions");
        w.AppendLine("{");
        w.AppendLine("    public static string ToElementId(this ElementTypeId id) => id switch");
        w.AppendLine("    {");
        foreach (var row in ordered)
            w.AppendLine($"        ElementTypeId.{Pascal(row.ElementId)} => \"{row.ElementId}\",");
        w.AppendLine("        _ => throw new ArgumentOutOfRangeException(nameof(id), id, \"Unknown element type.\")");
        w.AppendLine("    };");
        w.AppendLine("}");

        return w.ToString();
    }

    static string Pascal(string id) =>
        id.Length == 0 ? id : char.ToUpperInvariant(id[0]) + id[1..];
}
