using FusionRpg.Core.Battle;
using FusionRpg.Core.Effects.Atoms;

namespace FusionRpg.Tools.ElementEnumGen;

/// <summary>
/// Whether the hand-written <see cref="TraitAtomSource.Shipped"/> dictionary still agrees with the
/// migrated trait containers under <c>data/seed/containers/trait-*.json</c> (E23, completeness-audit
/// B2). Reuses <see cref="TraitAtomSource.FromContainers"/> directly — the exact resolution
/// <see cref="TraitMigrationParityTests"/> already exercises — rather than re-deriving it, so this
/// tool cannot disagree with the test suite about what "migrated" means.
/// </summary>
public static class TraitSourceCheck
{
    public static MismatchReport Run(SeedContent content)
    {
        var byId = content.Atoms.ToDictionary(a => a.AtomId, StringComparer.Ordinal);
        var migrated = TraitAtomSource.FromContainers(content.Containers, id => byId.GetValueOrDefault(id));
        var shipped = TraitAtomSource.Shipped();

        var traitIds = content.Containers
            .Where(c => c.Kind == ContainerKind.Trait)
            .Select(c => c.ContainerId.StartsWith("trait.", StringComparison.Ordinal)
                ? c.ContainerId["trait.".Length..]
                : null)
            .Where(id => id is not null)
            .Cast<string>()
            .Distinct(StringComparer.Ordinal)
            .OrderBy(id => id, StringComparer.Ordinal)
            .ToList();

        var mismatches = new List<string>();

        foreach (var id in traitIds)
        {
            if (!migrated.IsMigrated(id))
            {
                mismatches.Add($"'{id}' has a trait container but no stat.derived atom migrated it");
                continue;
            }

            if (!shipped.IsMigrated(id))
            {
                // ModsFor's fallback reads TraitBattleCatalog, which throws for a trait id it does
                // not know at all — must not be called before this check for an invented id.
                mismatches.Add(
                    $"'{id}' is migrated in data/seed/ but TraitAtomSource.Shipped() has no entry for it");
                continue;
            }

            var seedMods = migrated.ModsFor(id);
            var shippedMods = shipped.ModsFor(id);

            if (!seedMods.SequenceEqual(shippedMods))
                mismatches.Add(
                    $"'{id}': seed-derived mods [{string.Join(",", seedMods)}] != " +
                    $"TraitAtomSource.Shipped() [{string.Join(",", shippedMods)}]");
        }

        return new MismatchReport(mismatches);
    }

    /// <summary>
    /// The generated <c>Shipped()</c> body the migrated traits would carry — offered for review, same
    /// policy as <see cref="ElementEnumCheck.GenerateSource"/>.
    /// </summary>
    public static string GenerateSource(SeedContent content)
    {
        var byId = content.Atoms.ToDictionary(a => a.AtomId, StringComparer.Ordinal);
        var migrated = TraitAtomSource.FromContainers(content.Containers, id => byId.GetValueOrDefault(id));

        var traitIds = content.Containers
            .Where(c => c.Kind == ContainerKind.Trait)
            .Select(c => c.ContainerId.StartsWith("trait.", StringComparison.Ordinal)
                ? c.ContainerId["trait.".Length..]
                : null)
            .Where(id => id is not null && migrated.IsMigrated(id))
            .Cast<string>()
            .Distinct(StringComparer.Ordinal)
            .OrderBy(id => id, StringComparer.Ordinal)
            .ToList();

        var w = new System.Text.StringBuilder();
        w.AppendLine("// <auto-generated>");
        w.AppendLine("// Generated by tools/ElementEnumGen --trait-emit from data/seed/{atoms,containers}/trait-*.json.");
        w.AppendLine("// Do not hand-edit — edit the seed files and regenerate.");
        w.AppendLine("// </auto-generated>");
        w.AppendLine("public static TraitAtomSource Shipped() => new(new Dictionary<string, List<BattleChannelMod>>(");
        w.AppendLine("    StringComparer.Ordinal)");
        w.AppendLine("{");
        foreach (var id in traitIds)
        {
            w.AppendLine($"    [\"{id}\"] = new()");
            w.AppendLine("    {");
            foreach (var mod in migrated.ModsFor(id))
                w.AppendLine($"        new BattleChannelMod(Stats.Derived.DerivedStatChannels.{ChannelConstName(mod.ChannelId)}, {mod.Amount}),");
            w.AppendLine("    },");
        }
        w.AppendLine("});");

        return w.ToString();
    }

    /// <summary>
    /// Best-effort channel-id-to-constant-name guess for the generated source's readability — the
    /// generated file is for review, and a wrong guess here is a cosmetic miss, not a behaviour bug:
    /// <see cref="Run"/> compares by the channel STRING <see cref="TraitAtomSource"/> actually stores,
    /// never by this name.
    /// </summary>
    static string ChannelConstName(string channelId)
    {
        var parts = channelId.Split('.', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p[1..]));
    }
}
