"""Load the live demon seed roster used by action seeding.

The species seed folder is the source of truth. The generated C# catalog remains
available only as an explicit legacy compatibility input for older fixtures.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from ...demons.family.consolidate import FamilyCandidateInput, consolidate
from .curation import curated_traits

__all__ = [
    "SpeciesRow", "RARITY_LADDER", "TRAIT_POOL", "load_catalog", "load_live_records",
    "derive_live_family_assignments", "CATALOG_PATH", "LEGACY_CATALOG_PATH",
]

REPO_ROOT = Path(__file__).resolve().parents[6]
CATALOG_PATH = REPO_ROOT / "data" / "seed" / "demons" / "species"
LEGACY_CATALOG_PATH = REPO_ROOT / "src" / "FusionRpg.Core" / "Demons" / "DemonSpeciesCatalog.Generated.cs"

# `DemonRarityIds.ToId` — src/FusionRpg.Core/Demons/DemonRarity.cs:16-27 (enum declaration order,
# which the C# enum makes the ordinal — never re-derive an ordinal by sorting strings). Transcribed
# because there is no JSON export of the enum; a guard test pins the exact ids and count so a real
# enum change fails loudly rather than silently drifting (same discipline as
# `adapters/demons/registries.py`'s own header comment).
RARITY_LADDER: "tuple[str, ...]" = (
    "chaff", "sprout", "grafted", "cultivated", "fused",
    "chimeric", "heirloom", "firstseed", "sunwoven", "almanac",
)
RARITY_ORDINAL = {rid: i for i, rid in enumerate(RARITY_LADDER)}

# `DemonTraitCatalog.All` — src/FusionRpg.Core/Demons/DemonTraitCatalog.cs:11-30. The closed
# 14-member trait pool (spec §3 step 4's own citation), transcribed for the same "code, not data"
# reason as RARITY_LADDER above — never re-derived from a species scan, so a species whose
# `TraitPool` happens to omit one this run does not silently shrink the vocabulary.
TRAIT_POOL: "tuple[str, ...]" = (
    "berserker", "regenerator", "soul-eater", "critical-hunter", "guardian", "swift", "immortal",
    "loyal", "greedy", "bloodthirsty", "coward", "genius", "void-touched", "chaos-marked",
)

_ELEMENT_ID = {
    "Fire": "fire", "Ice": "ice", "Air": "air", "Earth": "earth", "Light": "light", "Dark": "dark",
}

# One `new() { ... }` object per species, on one line (the generator's own convention — see the
# file's own `<auto-generated>` header: "Regenerate: dotnet run --project tools/DemonCatalogGen").
_ROW_RE = re.compile(
    r'SpeciesId\s*=\s*"(?P<id>[a-z0-9]+)".*?'
    r'ElementPrimary\s*=\s*ElementTypeId\.(?P<elem_primary>\w+).*?'
    r'ElementSecondary\s*=\s*(?:ElementTypeId\.(?P<elem_secondary>\w+)|null).*?'
    r'BaseRarity\s*=\s*DemonRarity\.(?P<rarity>\w+).*?'
    r'TraitPool\s*=\s*new\[\]\s*\{\s*(?P<traits>[^}]*)\s*\}',
)
_TRAIT_STR_RE = re.compile(r'"([a-z-]+)"')

# DemonRarity enum member name -> ladder id (DemonRarityIds.ToId, DemonRarity.cs:52-65). The C#
# source spells the member in PascalCase; the ladder id is the same word lower-cased in every case
# here (Chaff -> "chaff", Sunwoven -> "sunwoven", ...), so a plain `.lower()` is the whole map —
# asserted by this module's own tests rather than assumed.
_RARITY_MEMBER_TO_ID = {rid.capitalize(): rid for rid in RARITY_LADDER}


@dataclass(frozen=True)
class SpeciesRow:
    species_id: str                     # lower-case, the canonical key (spec §3 step 1)
    element_primary: str                # one of ActorElementTypes' 6 ids
    element_secondary: "str | None"     # None when the species is pure (spec's own "none")
    rarity: str                         # the LADDER id — never the legacy band (spec §3 step 2)
    rarity_ordinal: int                 # DemonRarity.cs declaration order, 0..9
    traits: "tuple[str, ...]"           # the CLOSED 14-trait pool (curated, `curation.py`)
    raw_traits: "tuple[str, ...]" = ()  # the seed's own open flavor text, before curation — kept
                                        # for provenance only, never scored (see `curation.py`)


def _load_legacy_catalog(path: Path) -> "list[SpeciesRow]":
    """Parse an explicitly supplied legacy `.cs` roster for compatibility fixtures."""
    text = path.read_text(encoding="utf-8")
    rows: "list[SpeciesRow]" = []
    seen: "set[str]" = set()
    for m in _ROW_RE.finditer(text):
        sid = m.group("id")
        if sid in seen:
            raise ValueError(f"{path}: duplicate SpeciesId {sid!r} in the catalog")
        seen.add(sid)

        elem_primary = _ELEMENT_ID.get(m.group("elem_primary"))
        if elem_primary is None:
            raise ValueError(f"{path}: species {sid!r} — unknown ElementPrimary "
                             f"{m.group('elem_primary')!r}")
        elem_secondary_raw = m.group("elem_secondary")
        elem_secondary = _ELEMENT_ID.get(elem_secondary_raw) if elem_secondary_raw else None
        if elem_secondary_raw and elem_secondary is None:
            raise ValueError(f"{path}: species {sid!r} — unknown ElementSecondary "
                             f"{elem_secondary_raw!r}")

        rarity_member = m.group("rarity")
        rarity_id = _RARITY_MEMBER_TO_ID.get(rarity_member)
        if rarity_id is None:
            raise ValueError(f"{path}: species {sid!r} — unknown BaseRarity {rarity_member!r}")

        traits = tuple(_TRAIT_STR_RE.findall(m.group("traits")))
        unknown_traits = [t for t in traits if t not in TRAIT_POOL]
        if unknown_traits:
            raise ValueError(f"{path}: species {sid!r} — trait(s) {unknown_traits} outside the "
                             f"14-member closed pool")

        rows.append(SpeciesRow(
            species_id=sid, element_primary=elem_primary, element_secondary=elem_secondary,
            rarity=rarity_id, rarity_ordinal=RARITY_ORDINAL[rarity_id], traits=traits,
        ))
    if not rows:
        raise ValueError(f"{path}: matched zero species rows — the row pattern no longer fits "
                         f"the live file's shape")
    return rows


def load_live_records(root: Path = CATALOG_PATH) -> "list[dict[str, object]]":
    """Read every live species record from the seed folder in stable path order."""
    if not root.is_dir():
        raise ValueError(f"{root}: live species seed directory does not exist")

    records: "list[dict[str, object]]" = []
    seen: "set[str]" = set()
    for path in sorted(root.rglob("*.json")):
        if path.name == "_index.json":
            continue
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ValueError(f"{path}: invalid JSON: {exc}") from exc

        entries = payload if isinstance(payload, list) else [payload]
        for entry in entries:
            if not isinstance(entry, dict):
                raise ValueError(f"{path}: species record must be an object")
            raw_id = entry.get("speciesId")
            if not isinstance(raw_id, str) or not raw_id.strip():
                raise ValueError(f"{path}: species record is missing speciesId")
            species_id = raw_id.strip().lower()
            if species_id in seen:
                raise ValueError(f"{path}: duplicate speciesId {species_id!r}")
            seen.add(species_id)
            records.append({**entry, "speciesId": species_id, "_sourcePath": str(path)})

    if not records:
        raise ValueError(f"{root}: live species seed directory contains no species records")
    return records


def _live_row(record: dict[str, object]) -> SpeciesRow:
    path = record.get("_sourcePath", "live species seed")
    species_id = record["speciesId"]
    if not isinstance(species_id, str):
        raise ValueError(f"{path}: speciesId must be a string")

    primary = record.get("elementPrimary")
    secondary = record.get("elementSecondary")
    valid_elements = {"fire", "ice", "air", "earth", "light", "dark"}
    primary_id = primary.lower() if isinstance(primary, str) else ""
    secondary_id = secondary.lower() if isinstance(secondary, str) and secondary.lower() != "none" else None
    if primary_id not in valid_elements:
        raise ValueError(f"{path}: species {species_id!r} has unknown elementPrimary {primary!r}")
    if secondary_id is not None and secondary_id not in valid_elements:
        raise ValueError(f"{path}: species {species_id!r} has unknown elementSecondary {secondary!r}")
    if secondary_id == primary_id:
        secondary_id = None

    rarity = record.get("rarity")
    rarity_id = rarity.lower() if isinstance(rarity, str) else ""
    if rarity_id not in RARITY_ORDINAL:
        raise ValueError(f"{path}: species {species_id!r} has unknown rarity {rarity!r}")

    raw_traits = record.get("traits", [])
    if not isinstance(raw_traits, list):
        raise ValueError(f"{path}: species {species_id!r} traits must be a list")
    raw = tuple(str(trait).strip().lower() for trait in raw_traits if str(trait).strip())

    # The live seed's `traits` field is open flavor text (measured 2026-09-11: 2,312 distinct
    # tokens, one of which is a closed-pool member). Score the CLOSED pool the game actually gives
    # this species — `DemonTraitPoolCuration.PickFor`'s own bridge, mirrored in `curation.py` — and
    # keep the raw text only for provenance. See `curation.py` for the full defect account.
    game_type_id = record.get("gameTypeId")
    traits = curated_traits(
        species_id, rarity_id,
        game_type_id if isinstance(game_type_id, int) and not isinstance(game_type_id, bool) else 0)
    return SpeciesRow(
        species_id=species_id,
        element_primary=primary_id,
        element_secondary=secondary_id,
        rarity=rarity_id,
        rarity_ordinal=RARITY_ORDINAL[rarity_id],
        traits=traits, raw_traits=raw,
    )


def normalize_family_key(label: str) -> str:
    """Turn a live descriptive family label into a stable action namespace key."""
    key = re.sub(r"[^a-z0-9]+", "-", label.strip().lower()).strip("-")
    if not key:
        raise ValueError(f"family label {label!r} normalizes to an empty key")
    return key


def derive_live_family_assignments(root: Path = CATALOG_PATH) -> "dict[str, list[str]]":
    """Derive species-to-family memberships from the live species records."""
    candidates: "list[FamilyCandidateInput]" = []
    for record in load_live_records(root):
        raw_families = record.get("family", [])
        if isinstance(raw_families, str):
            raw_families = [raw_families]
        if not isinstance(raw_families, list):
            raise ValueError(f"{record['_sourcePath']}: family must be a list")
        labels = sorted({str(label).strip() for label in raw_families if str(label).strip()})
        if not labels:
            raise ValueError(f"{record['_sourcePath']}: species {record['speciesId']!r} has no family")
        for label in labels:
            candidates.append(FamilyCandidateInput(
                species_id=str(record["speciesId"]), label=label,
                native_label=label, basis="text",
            ))
    return consolidate(candidates).assignments


def load_catalog(path: Path = CATALOG_PATH) -> "list[SpeciesRow]":
    """Load the live seed roster, or parse an explicitly supplied legacy C# file."""
    if path.is_dir():
        return [_live_row(record) for record in load_live_records(path)]
    return _load_legacy_catalog(path)
