"""seedsmith.adapters.actions.characteristic_pool.catalog — the 84-species roster (spec §2's
first "Reads" row), parsed straight from the C# code of record. No JSON export of this table
exists, so — same "code, not data" precedent `adapters/demons/registries.py`'s own docstring
already establishes for this exact file family — this module transcribes the *parser*, never the
*data*: every run reads the live `.cs` file fresh, so a roster change is picked up automatically
and this module never drifts from it the way a hand-copied constant would.

Constraint 3 (map §3 / spec's own §1): the roster is the **84** `SpeciesId` rows here, never the
904-row almanac. `DemonSpeciesCatalog.Generated.cs` line numbers are cited relative to the file
read at build time (2026-09-03: 84 entries, `:14-97`) — re-verified directly against the live file
by this module's own tests rather than trusted from the spec's citation, per this repo's own
design-gate discipline (A-C1's build found two stale citations in this exact file family).
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

__all__ = [
    "SpeciesRow", "RARITY_LADDER", "TRAIT_POOL", "load_catalog", "CATALOG_PATH",
]

REPO_ROOT = Path(__file__).resolve().parents[6]
CATALOG_PATH = REPO_ROOT / "src" / "FusionRpg.Core" / "Demons" / "DemonSpeciesCatalog.Generated.cs"

# `DemonRarityIds.ToId` — src/FusionRpg.Core/Demons/DemonRarity.cs:16-27 (enum declaration order,
# which the C# enum makes the ordinal — never re-derive an ordinal by sorting strings). Transcribed
# because there is no JSON export of the enum; a guard test pins the exact ids and count so a real
# enum change fails loudly rather than silently drifting (same discipline as
# `adapters/demons/registries.py`'s own header comment).
RARITY_LADDER: "tuple[str, ...]" = (
    "chaff", "sprout", "grafted", "cultivated", "fused",
    "chimeric", "heirloom", "firstseed", "sunwoven", "almanac",
)
RARITY_ORDINAL = {rid: i for i, rid in enumerate(RARITY_LADDER)}

# `DemonTraitCatalog.All` — src/FusionRpg.Core/Demons/DemonTraitCatalog.cs:11-30. The closed
# 14-member trait pool (spec §3 step 4's own citation), transcribed for the same "code, not data"
# reason as RARITY_LADDER above — never re-derived from a species scan, so a species whose
# `TraitPool` happens to omit one this run does not silently shrink the vocabulary.
TRAIT_POOL: "tuple[str, ...]" = (
    "berserker", "regenerator", "soul-eater", "critical-hunter", "guardian", "swift", "immortal",
    "loyal", "greedy", "bloodthirsty", "coward", "genius", "void-touched", "chaos-marked",
)

_ELEMENT_ID = {
    "Fire": "fire", "Ice": "ice", "Air": "air", "Earth": "earth", "Light": "light", "Dark": "dark",
}

# One `new() { ... }` object per species, on one line (the generator's own convention — see the
# file's own `<auto-generated>` header: "Regenerate: dotnet run --project tools/DemonCatalogGen").
_ROW_RE = re.compile(
    r'SpeciesId\s*=\s*"(?P<id>[a-z0-9]+)".*?'
    r'ElementPrimary\s*=\s*ElementTypeId\.(?P<elem_primary>\w+).*?'
    r'ElementSecondary\s*=\s*(?:ElementTypeId\.(?P<elem_secondary>\w+)|null).*?'
    r'BaseRarity\s*=\s*DemonRarity\.(?P<rarity>\w+).*?'
    r'TraitPool\s*=\s*new\[\]\s*\{\s*(?P<traits>[^}]*)\s*\}',
)
_TRAIT_STR_RE = re.compile(r'"([a-z-]+)"')

# DemonRarity enum member name -> ladder id (DemonRarityIds.ToId, DemonRarity.cs:52-65). The C#
# source spells the member in PascalCase; the ladder id is the same word lower-cased in every case
# here (Chaff -> "chaff", Sunwoven -> "sunwoven", ...), so a plain `.lower()` is the whole map —
# asserted by this module's own tests rather than assumed.
_RARITY_MEMBER_TO_ID = {rid.capitalize(): rid for rid in RARITY_LADDER}


@dataclass(frozen=True)
class SpeciesRow:
    species_id: str                     # lower-case, the canonical key (spec §3 step 1)
    element_primary: str                # one of ActorElementTypes' 6 ids
    element_secondary: "str | None"     # None when the species is pure (spec's own "none")
    rarity: str                         # the LADDER id — never the legacy band (spec §3 step 2)
    rarity_ordinal: int                 # DemonRarity.cs declaration order, 0..9
    traits: "tuple[str, ...]"           # this species' own TraitPool, catalog order preserved


def load_catalog(path: Path = CATALOG_PATH) -> "list[SpeciesRow]":
    """Parse the live `.cs` roster in file (= catalog) order — step 2's own requirement ("per
    species, in catalog order"). Raises `ValueError` naming the unparsed fragment rather than
    silently skipping a malformed row: a roster this module cannot fully read is a build-stopping
    problem, not a `Finding` (unlike A-C1's corpus content, this file is not player-authored)."""
    text = path.read_text(encoding="utf-8")
    rows: "list[SpeciesRow]" = []
    seen: "set[str]" = set()
    for m in _ROW_RE.finditer(text):
        sid = m.group("id")
        if sid in seen:
            raise ValueError(f"{path}: duplicate SpeciesId {sid!r} in the catalog")
        seen.add(sid)

        elem_primary = _ELEMENT_ID.get(m.group("elem_primary"))
        if elem_primary is None:
            raise ValueError(f"{path}: species {sid!r} — unknown ElementPrimary "
                             f"{m.group('elem_primary')!r}")
        elem_secondary_raw = m.group("elem_secondary")
        elem_secondary = _ELEMENT_ID.get(elem_secondary_raw) if elem_secondary_raw else None
        if elem_secondary_raw and elem_secondary is None:
            raise ValueError(f"{path}: species {sid!r} — unknown ElementSecondary "
                             f"{elem_secondary_raw!r}")

        rarity_member = m.group("rarity")
        rarity_id = _RARITY_MEMBER_TO_ID.get(rarity_member)
        if rarity_id is None:
            raise ValueError(f"{path}: species {sid!r} — unknown BaseRarity {rarity_member!r}")

        traits = tuple(_TRAIT_STR_RE.findall(m.group("traits")))
        unknown_traits = [t for t in traits if t not in TRAIT_POOL]
        if unknown_traits:
            raise ValueError(f"{path}: species {sid!r} — trait(s) {unknown_traits} outside the "
                             f"14-member closed pool")

        rows.append(SpeciesRow(
            species_id=sid, element_primary=elem_primary, element_secondary=elem_secondary,
            rarity=rarity_id, rarity_ordinal=RARITY_ORDINAL[rarity_id], traits=traits,
        ))
    if not rows:
        raise ValueError(f"{path}: matched zero species rows — the row pattern no longer fits "
                         f"the live file's shape")
    return rows
