namespace FusionRpg.Core.Effects.Atoms;

/// <summary>
/// `instance-producer` (T3.6, `spec-instance-producer.md`, ⭐ the payoff): composes a real
/// <see cref="InstanceRow"/> — fixed core frozen (E6), pool half resolved through the affix-aware
/// five-step order (module 2, `Resolver.Resolve`) instead of <see cref="Instantiator.Draw"/>'s
/// single-ref-only path. Every real decision already lives one layer down; this is the wiring.
///
/// <para><b>Core stays free of I/O</b> (the same discipline every module in this program follows) —
/// this composes the row, it does not persist it. The spec's own pseudocode signature takes an
/// `RpgStore` directly and returns a binding id in one call; that cannot compile inside Core (`Data`
/// depends on `Core`, never the other way — verified against both `.csproj` files, not assumed), and
/// <c>BindingRow</c> itself is a <c>FusionRpg.Data</c> type. This module's real shape therefore splits
/// at the layer boundary: this composes the <see cref="InstanceRow"/>; the real caller
/// (<c>RpgStore.ProduceAndBind</c>, `FusionRpg.Data`) wraps it in a <c>BindingRow</c> and persists
/// both atomically. A deliberate, documented deviation from the spec's stated file placement, not an
/// oversight.</para>
/// </summary>
public static class InstanceProducer
{
    /// <summary>
    /// Compose one instance: the fixed core frozen exactly as <see cref="Instantiator.TryInstantiate"/>
    /// already does, the pool half drawn through <see cref="Resolver.Resolve"/> instead of
    /// <see cref="Instantiator.Draw"/> — the affix-aware replacement this whole program exists to wire
    /// in. <c>PowerJson</c> stays null on every row: power is backfilled later (E9), never computed on
    /// this path (`effect-pipeline-ideal.md` A3).
    /// </summary>
    public static AtomRejection Compose(
        ContainerRow container,
        Func<string, AtomRow?> lookupAtom,
        Func<string, AffixRow?> lookupAffix,
        Func<string, IReadOnlyList<string>> domainMembers,
        long rollSeed,
        int thetaContent,
        FusionRpg.Core.Power.PowerTuning tuning,
        out InstanceRow? instance,
        VariantShift? variant = null,
        InstanceOrigin origin = InstanceOrigin.Drop,
        long catalogRevision = 0)
    {
        instance = null;

        var check = ContainerValidator.Validate(container, lookupAtom, lookupAffix);
        if (!check.IsOk) return check;

        var contentScaleMilli = FusionRpg.Core.Power.ContentScale.Milli(thetaContent, tuning);

        var rows = new List<InstanceAtomRow>();
        foreach (var entry in container.Atoms.OrderBy(a => a.Seq))
        {
            var atom = lookupAtom(entry.AtomId)!;
            var freeze = Instantiator.Freeze(
                atom, entry.OverridesJson, rollSeed, entry.Seq, contentScaleMilli, out var valuesJson);
            if (!freeze.IsOk) return freeze;

            rows.Add(new InstanceAtomRow(entry.Seq, entry.AtomId, valuesJson));
        }

        var drawn = Resolver.Resolve(
            container, lookupAtom, lookupAffix, domainMembers, rollSeed, variant, contentScaleMilli);
        var nextSeq = rows.Count == 0 ? 1 : rows.Max(r => r.Seq) + 1;

        foreach (var a in drawn.Atoms)
        {
            rows.Add(new InstanceAtomRow(nextSeq, a.AtomId, a.ValuesJson));
            nextSeq++;
        }

        instance = new InstanceRow
        {
            InstanceId = "",       // generated by the store; excluded from the fingerprint
            ContainerId = container.ContainerId,
            RollSeed = rollSeed,
            CatalogRevision = catalogRevision,
            Origin = origin,
            Atoms = rows,
            ThetaContent = thetaContent,
            ContentScaleMilli = contentScaleMilli,
        };
        return AtomRejection.Ok;
    }
}
